# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\New folder\AOO.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AOO_mode(object):
    def setupUi(self, AOO_mode):
        AOO_mode.setObjectName("AOO_mode")
        AOO_mode.resize(700, 400)
        AOO_mode.setSizeGripEnabled(True)
        self.label = QtWidgets.QLabel(AOO_mode)
        self.label.setGeometry(QtCore.QRect(60, 60, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AOO_mode)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayoutWidget = QtWidgets.QWidget(AOO_mode)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 150, 341, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.pushButton = QtWidgets.QPushButton(AOO_mode)
        self.pushButton.setGeometry(QtCore.QRect(210, 320, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AOO_mode)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 320, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(AOO_mode)
        QtCore.QMetaObject.connectSlotsByName(AOO_mode)

    def retranslateUi(self, AOO_mode):
        _translate = QtCore.QCoreApplication.translate
        AOO_mode.setWindowTitle(_translate("AOO_mode", "AOO Parameter Change"))
        self.label.setText(_translate("AOO_mode", "Mode:AOO"))
        self.label_2.setText(_translate("AOO_mode", "View and Change your parameters"))
        self.label_3.setText(_translate("AOO_mode", "LOWER RATE LIMIT(PPM)"))
        self.label_4.setText(_translate("AOO_mode", "UPPER RATE LIMIT(PPM)"))
        self.label_5.setText(_translate("AOO_mode", "ATRIAL AMPLITUDE(V)"))
        self.label_7.setText(_translate("AOO_mode", "ATRIAL PULSE WIDTH(ms)"))
        self.comboBox_5.setItemText(1, _translate("AOO_mode", "30"))
        self.comboBox_5.setItemText(2, _translate("AOO_mode", "35"))
        self.comboBox_5.setItemText(3, _translate("AOO_mode", "40"))
        self.comboBox_5.setItemText(4, _translate("AOO_mode", "45"))
        self.comboBox_5.setItemText(5, _translate("AOO_mode", "50"))
        self.comboBox_5.setItemText(6, _translate("AOO_mode", "51"))
        self.comboBox_5.setItemText(7, _translate("AOO_mode", "52"))
        self.comboBox_5.setItemText(8, _translate("AOO_mode", "53"))
        self.comboBox_5.setItemText(9, _translate("AOO_mode", "54"))
        self.comboBox_5.setItemText(10, _translate("AOO_mode", "55"))
        self.comboBox_5.setItemText(11, _translate("AOO_mode", "56"))
        self.comboBox_5.setItemText(12, _translate("AOO_mode", "57"))
        self.comboBox_5.setItemText(13, _translate("AOO_mode", "58"))
        self.comboBox_5.setItemText(14, _translate("AOO_mode", "59"))
        self.comboBox_5.setItemText(15, _translate("AOO_mode", "60"))
        self.comboBox_5.setItemText(16, _translate("AOO_mode", "61"))
        self.comboBox_5.setItemText(17, _translate("AOO_mode", "62"))
        self.comboBox_5.setItemText(18, _translate("AOO_mode", "63"))
        self.comboBox_5.setItemText(19, _translate("AOO_mode", "64"))
        self.comboBox_5.setItemText(20, _translate("AOO_mode", "65"))
        self.comboBox_5.setItemText(21, _translate("AOO_mode", "66"))
        self.comboBox_5.setItemText(22, _translate("AOO_mode", "67"))
        self.comboBox_5.setItemText(23, _translate("AOO_mode", "68"))
        self.comboBox_5.setItemText(24, _translate("AOO_mode", "69"))
        self.comboBox_5.setItemText(25, _translate("AOO_mode", "70"))
        self.comboBox_5.setItemText(26, _translate("AOO_mode", "71"))
        self.comboBox_5.setItemText(27, _translate("AOO_mode", "72"))
        self.comboBox_5.setItemText(28, _translate("AOO_mode", "73"))
        self.comboBox_5.setItemText(29, _translate("AOO_mode", "74"))
        self.comboBox_5.setItemText(30, _translate("AOO_mode", "75"))
        self.comboBox_5.setItemText(31, _translate("AOO_mode", "76"))
        self.comboBox_5.setItemText(32, _translate("AOO_mode", "77"))
        self.comboBox_5.setItemText(33, _translate("AOO_mode", "78"))
        self.comboBox_5.setItemText(34, _translate("AOO_mode", "79"))
        self.comboBox_5.setItemText(35, _translate("AOO_mode", "80"))
        self.comboBox_5.setItemText(36, _translate("AOO_mode", "81"))
        self.comboBox_5.setItemText(37, _translate("AOO_mode", "82"))
        self.comboBox_5.setItemText(38, _translate("AOO_mode", "83"))
        self.comboBox_5.setItemText(39, _translate("AOO_mode", "84"))
        self.comboBox_5.setItemText(40, _translate("AOO_mode", "85"))
        self.comboBox_5.setItemText(41, _translate("AOO_mode", "86"))
        self.comboBox_5.setItemText(42, _translate("AOO_mode", "87"))
        self.comboBox_5.setItemText(43, _translate("AOO_mode", "88"))
        self.comboBox_5.setItemText(44, _translate("AOO_mode", "89"))
        self.comboBox_5.setItemText(45, _translate("AOO_mode", "90"))
        self.comboBox_5.setItemText(46, _translate("AOO_mode", "95"))
        self.comboBox_5.setItemText(47, _translate("AOO_mode", "100"))
        self.comboBox_5.setItemText(48, _translate("AOO_mode", "105"))
        self.comboBox_5.setItemText(49, _translate("AOO_mode", "110"))
        self.comboBox_5.setItemText(50, _translate("AOO_mode", "115"))
        self.comboBox_5.setItemText(51, _translate("AOO_mode", "120"))
        self.comboBox_5.setItemText(52, _translate("AOO_mode", "125"))
        self.comboBox_5.setItemText(53, _translate("AOO_mode", "130"))
        self.comboBox_5.setItemText(54, _translate("AOO_mode", "135"))
        self.comboBox_5.setItemText(55, _translate("AOO_mode", "140"))
        self.comboBox_5.setItemText(56, _translate("AOO_mode", "145"))
        self.comboBox_5.setItemText(57, _translate("AOO_mode", "150"))
        self.comboBox_5.setItemText(58, _translate("AOO_mode", "155"))
        self.comboBox_5.setItemText(59, _translate("AOO_mode", "160"))
        self.comboBox_5.setItemText(60, _translate("AOO_mode", "165"))
        self.comboBox_5.setItemText(61, _translate("AOO_mode", "170"))
        self.comboBox_5.setItemText(62, _translate("AOO_mode", "175"))
        self.comboBox_4.setItemText(1, _translate("AOO_mode", "50"))
        self.comboBox_4.setItemText(2, _translate("AOO_mode", "55"))
        self.comboBox_4.setItemText(3, _translate("AOO_mode", "60"))
        self.comboBox_4.setItemText(4, _translate("AOO_mode", "65"))
        self.comboBox_4.setItemText(5, _translate("AOO_mode", "70"))
        self.comboBox_4.setItemText(6, _translate("AOO_mode", "75"))
        self.comboBox_4.setItemText(7, _translate("AOO_mode", "80"))
        self.comboBox_4.setItemText(8, _translate("AOO_mode", "85"))
        self.comboBox_4.setItemText(9, _translate("AOO_mode", "90"))
        self.comboBox_4.setItemText(10, _translate("AOO_mode", "95"))
        self.comboBox_4.setItemText(11, _translate("AOO_mode", "100"))
        self.comboBox_4.setItemText(12, _translate("AOO_mode", "105"))
        self.comboBox_4.setItemText(13, _translate("AOO_mode", "110"))
        self.comboBox_4.setItemText(14, _translate("AOO_mode", "115"))
        self.comboBox_4.setItemText(15, _translate("AOO_mode", "120"))
        self.comboBox_4.setItemText(16, _translate("AOO_mode", "125"))
        self.comboBox_4.setItemText(17, _translate("AOO_mode", "130"))
        self.comboBox_4.setItemText(18, _translate("AOO_mode", "135"))
        self.comboBox_4.setItemText(19, _translate("AOO_mode", "140"))
        self.comboBox_4.setItemText(20, _translate("AOO_mode", "145"))
        self.comboBox_4.setItemText(21, _translate("AOO_mode", "150"))
        self.comboBox_4.setItemText(22, _translate("AOO_mode", "155"))
        self.comboBox_4.setItemText(23, _translate("AOO_mode", "160"))
        self.comboBox_4.setItemText(24, _translate("AOO_mode", "165"))
        self.comboBox_4.setItemText(25, _translate("AOO_mode", "170"))
        self.comboBox_4.setItemText(26, _translate("AOO_mode", "175"))
        self.comboBox_3.setItemText(1, _translate("AOO_mode", "1.25"))
        self.comboBox_3.setItemText(2, _translate("AOO_mode", "2.5"))
        self.comboBox_3.setItemText(3, _translate("AOO_mode", "3.75"))
        self.comboBox_3.setItemText(4, _translate("AOO_mode", "5.0"))
        self.comboBox_2.setItemText(1, _translate("AOO_mode", "0.05"))
        self.comboBox_2.setItemText(2, _translate("AOO_mode", "0.1"))
        self.comboBox_2.setItemText(3, _translate("AOO_mode", "0.2"))
        self.comboBox_2.setItemText(4, _translate("AOO_mode", "0.3"))
        self.comboBox_2.setItemText(5, _translate("AOO_mode", "0.4"))
        self.comboBox_2.setItemText(6, _translate("AOO_mode", "0.5"))
        self.comboBox_2.setItemText(7, _translate("AOO_mode", "0.6"))
        self.comboBox_2.setItemText(8, _translate("AOO_mode", "0.7"))
        self.comboBox_2.setItemText(9, _translate("AOO_mode", "0.8"))
        self.comboBox_2.setItemText(10, _translate("AOO_mode", "0.9"))
        self.comboBox_2.setItemText(11, _translate("AOO_mode", "1.0"))
        self.comboBox_2.setItemText(12, _translate("AOO_mode", "1.1"))
        self.comboBox_2.setItemText(13, _translate("AOO_mode", "1.2"))
        self.comboBox_2.setItemText(14, _translate("AOO_mode", "1.3"))
        self.comboBox_2.setItemText(15, _translate("AOO_mode", "1.4"))
        self.comboBox_2.setItemText(16, _translate("AOO_mode", "1.5"))
        self.comboBox_2.setItemText(17, _translate("AOO_mode", "1.6"))
        self.comboBox_2.setItemText(18, _translate("AOO_mode", "1.7"))
        self.comboBox_2.setItemText(19, _translate("AOO_mode", "1.8"))
        self.comboBox_2.setItemText(20, _translate("AOO_mode", "1.9"))
        self.pushButton.setText(_translate("AOO_mode", "Confirm"))
        self.pushButton_2.setText(_translate("AOO_mode", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AOO_mode = QtWidgets.QDialog()
    ui = Ui_AOO_mode()
    ui.setupUi(AOO_mode)
    AOO_mode.show()
    sys.exit(app.exec_())
