# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\New folder\AOOR.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AOOR_mode(object):
    def setupUi(self, AOOR_mode):
        AOOR_mode.setObjectName("AOOR_mode")
        AOOR_mode.resize(700, 400)
        AOOR_mode.setSizeGripEnabled(True)
        self.label = QtWidgets.QLabel(AOOR_mode)
        self.label.setGeometry(QtCore.QRect(40, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Qlabel = QtWidgets.QLabel(AOOR_mode)
        self.Qlabel.setGeometry(QtCore.QRect(40, 70, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Qlabel.setFont(font)
        self.Qlabel.setObjectName("Qlabel")
        self.formLayoutWidget = QtWidgets.QWidget(AOOR_mode)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 100, 461, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.comboBox_23 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.setItemText(0, "")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_23)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.comboBox_25 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.setItemText(0, "")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_25)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.comboBox_26 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.setItemText(0, "")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_26)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.comboBox_27 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.comboBox_27.setItemText(0, "")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_27)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.comboBox_28 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.setItemText(0, "")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_28)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboBox_29 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.setItemText(0, "")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_29)
        self.comboBox_24 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.setItemText(0, "")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_24)
        self.pushButton_2 = QtWidgets.QPushButton(AOOR_mode)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 350, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(AOOR_mode)
        self.pushButton.setGeometry(QtCore.QRect(470, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(AOOR_mode)
        QtCore.QMetaObject.connectSlotsByName(AOOR_mode)

    def retranslateUi(self, AOOR_mode):
        _translate = QtCore.QCoreApplication.translate
        AOOR_mode.setWindowTitle(_translate("AOOR_mode", "AOOR Parameters Change"))
        self.label.setText(_translate("AOOR_mode", "Mode:AOOR"))
        self.Qlabel.setText(_translate("AOOR_mode", "View and Change your parameters"))
        self.label_3.setText(_translate("AOOR_mode", "LOWER RATE LIMIT(PPM)"))
        self.comboBox_5.setItemText(1, _translate("AOOR_mode", "30"))
        self.comboBox_5.setItemText(2, _translate("AOOR_mode", "35"))
        self.comboBox_5.setItemText(3, _translate("AOOR_mode", "40"))
        self.comboBox_5.setItemText(4, _translate("AOOR_mode", "45"))
        self.comboBox_5.setItemText(5, _translate("AOOR_mode", "50"))
        self.comboBox_5.setItemText(6, _translate("AOOR_mode", "51"))
        self.comboBox_5.setItemText(7, _translate("AOOR_mode", "52"))
        self.comboBox_5.setItemText(8, _translate("AOOR_mode", "53"))
        self.comboBox_5.setItemText(9, _translate("AOOR_mode", "54"))
        self.comboBox_5.setItemText(10, _translate("AOOR_mode", "55"))
        self.comboBox_5.setItemText(11, _translate("AOOR_mode", "56"))
        self.comboBox_5.setItemText(12, _translate("AOOR_mode", "57"))
        self.comboBox_5.setItemText(13, _translate("AOOR_mode", "58"))
        self.comboBox_5.setItemText(14, _translate("AOOR_mode", "59"))
        self.comboBox_5.setItemText(15, _translate("AOOR_mode", "60"))
        self.comboBox_5.setItemText(16, _translate("AOOR_mode", "61"))
        self.comboBox_5.setItemText(17, _translate("AOOR_mode", "62"))
        self.comboBox_5.setItemText(18, _translate("AOOR_mode", "63"))
        self.comboBox_5.setItemText(19, _translate("AOOR_mode", "64"))
        self.comboBox_5.setItemText(20, _translate("AOOR_mode", "65"))
        self.comboBox_5.setItemText(21, _translate("AOOR_mode", "66"))
        self.comboBox_5.setItemText(22, _translate("AOOR_mode", "67"))
        self.comboBox_5.setItemText(23, _translate("AOOR_mode", "68"))
        self.comboBox_5.setItemText(24, _translate("AOOR_mode", "69"))
        self.comboBox_5.setItemText(25, _translate("AOOR_mode", "70"))
        self.comboBox_5.setItemText(26, _translate("AOOR_mode", "71"))
        self.comboBox_5.setItemText(27, _translate("AOOR_mode", "72"))
        self.comboBox_5.setItemText(28, _translate("AOOR_mode", "73"))
        self.comboBox_5.setItemText(29, _translate("AOOR_mode", "74"))
        self.comboBox_5.setItemText(30, _translate("AOOR_mode", "75"))
        self.comboBox_5.setItemText(31, _translate("AOOR_mode", "76"))
        self.comboBox_5.setItemText(32, _translate("AOOR_mode", "77"))
        self.comboBox_5.setItemText(33, _translate("AOOR_mode", "78"))
        self.comboBox_5.setItemText(34, _translate("AOOR_mode", "79"))
        self.comboBox_5.setItemText(35, _translate("AOOR_mode", "80"))
        self.comboBox_5.setItemText(36, _translate("AOOR_mode", "81"))
        self.comboBox_5.setItemText(37, _translate("AOOR_mode", "82"))
        self.comboBox_5.setItemText(38, _translate("AOOR_mode", "83"))
        self.comboBox_5.setItemText(39, _translate("AOOR_mode", "84"))
        self.comboBox_5.setItemText(40, _translate("AOOR_mode", "85"))
        self.comboBox_5.setItemText(41, _translate("AOOR_mode", "86"))
        self.comboBox_5.setItemText(42, _translate("AOOR_mode", "87"))
        self.comboBox_5.setItemText(43, _translate("AOOR_mode", "88"))
        self.comboBox_5.setItemText(44, _translate("AOOR_mode", "89"))
        self.comboBox_5.setItemText(45, _translate("AOOR_mode", "90"))
        self.comboBox_5.setItemText(46, _translate("AOOR_mode", "95"))
        self.comboBox_5.setItemText(47, _translate("AOOR_mode", "100"))
        self.comboBox_5.setItemText(48, _translate("AOOR_mode", "105"))
        self.comboBox_5.setItemText(49, _translate("AOOR_mode", "110"))
        self.comboBox_5.setItemText(50, _translate("AOOR_mode", "115"))
        self.comboBox_5.setItemText(51, _translate("AOOR_mode", "120"))
        self.comboBox_5.setItemText(52, _translate("AOOR_mode", "125"))
        self.comboBox_5.setItemText(53, _translate("AOOR_mode", "130"))
        self.comboBox_5.setItemText(54, _translate("AOOR_mode", "135"))
        self.comboBox_5.setItemText(55, _translate("AOOR_mode", "140"))
        self.comboBox_5.setItemText(56, _translate("AOOR_mode", "145"))
        self.comboBox_5.setItemText(57, _translate("AOOR_mode", "150"))
        self.comboBox_5.setItemText(58, _translate("AOOR_mode", "155"))
        self.comboBox_5.setItemText(59, _translate("AOOR_mode", "160"))
        self.comboBox_5.setItemText(60, _translate("AOOR_mode", "165"))
        self.comboBox_5.setItemText(61, _translate("AOOR_mode", "170"))
        self.comboBox_5.setItemText(62, _translate("AOOR_mode", "175"))
        self.label_4.setText(_translate("AOOR_mode", "UPPER RATE LIMIT(PPM)"))
        self.comboBox_4.setItemText(1, _translate("AOOR_mode", "50"))
        self.comboBox_4.setItemText(2, _translate("AOOR_mode", "55"))
        self.comboBox_4.setItemText(3, _translate("AOOR_mode", "60"))
        self.comboBox_4.setItemText(4, _translate("AOOR_mode", "65"))
        self.comboBox_4.setItemText(5, _translate("AOOR_mode", "70"))
        self.comboBox_4.setItemText(6, _translate("AOOR_mode", "75"))
        self.comboBox_4.setItemText(7, _translate("AOOR_mode", "80"))
        self.comboBox_4.setItemText(8, _translate("AOOR_mode", "85"))
        self.comboBox_4.setItemText(9, _translate("AOOR_mode", "90"))
        self.comboBox_4.setItemText(10, _translate("AOOR_mode", "95"))
        self.comboBox_4.setItemText(11, _translate("AOOR_mode", "100"))
        self.comboBox_4.setItemText(12, _translate("AOOR_mode", "105"))
        self.comboBox_4.setItemText(13, _translate("AOOR_mode", "110"))
        self.comboBox_4.setItemText(14, _translate("AOOR_mode", "115"))
        self.comboBox_4.setItemText(15, _translate("AOOR_mode", "120"))
        self.comboBox_4.setItemText(16, _translate("AOOR_mode", "125"))
        self.comboBox_4.setItemText(17, _translate("AOOR_mode", "130"))
        self.comboBox_4.setItemText(18, _translate("AOOR_mode", "135"))
        self.comboBox_4.setItemText(19, _translate("AOOR_mode", "140"))
        self.comboBox_4.setItemText(20, _translate("AOOR_mode", "145"))
        self.comboBox_4.setItemText(21, _translate("AOOR_mode", "150"))
        self.comboBox_4.setItemText(22, _translate("AOOR_mode", "155"))
        self.comboBox_4.setItemText(23, _translate("AOOR_mode", "160"))
        self.comboBox_4.setItemText(24, _translate("AOOR_mode", "165"))
        self.comboBox_4.setItemText(25, _translate("AOOR_mode", "170"))
        self.comboBox_4.setItemText(26, _translate("AOOR_mode", "175"))
        self.label_25.setText(_translate("AOOR_mode", "MAXIMUM SENSOR RATE(PPM)"))
        self.comboBox_23.setItemText(1, _translate("AOOR_mode", "50"))
        self.comboBox_23.setItemText(2, _translate("AOOR_mode", "55"))
        self.comboBox_23.setItemText(3, _translate("AOOR_mode", "60"))
        self.comboBox_23.setItemText(4, _translate("AOOR_mode", "65"))
        self.comboBox_23.setItemText(5, _translate("AOOR_mode", "70"))
        self.comboBox_23.setItemText(6, _translate("AOOR_mode", "75"))
        self.comboBox_23.setItemText(7, _translate("AOOR_mode", "80"))
        self.comboBox_23.setItemText(8, _translate("AOOR_mode", "85"))
        self.comboBox_23.setItemText(9, _translate("AOOR_mode", "90"))
        self.comboBox_23.setItemText(10, _translate("AOOR_mode", "95"))
        self.comboBox_23.setItemText(11, _translate("AOOR_mode", "100"))
        self.comboBox_23.setItemText(12, _translate("AOOR_mode", "105"))
        self.comboBox_23.setItemText(13, _translate("AOOR_mode", "110"))
        self.comboBox_23.setItemText(14, _translate("AOOR_mode", "115"))
        self.comboBox_23.setItemText(15, _translate("AOOR_mode", "120"))
        self.comboBox_23.setItemText(16, _translate("AOOR_mode", "125"))
        self.comboBox_23.setItemText(17, _translate("AOOR_mode", "130"))
        self.comboBox_23.setItemText(18, _translate("AOOR_mode", "135"))
        self.comboBox_23.setItemText(19, _translate("AOOR_mode", "140"))
        self.comboBox_23.setItemText(20, _translate("AOOR_mode", "145"))
        self.comboBox_23.setItemText(21, _translate("AOOR_mode", "150"))
        self.comboBox_23.setItemText(22, _translate("AOOR_mode", "155"))
        self.comboBox_23.setItemText(23, _translate("AOOR_mode", "160"))
        self.comboBox_23.setItemText(24, _translate("AOOR_mode", "165"))
        self.comboBox_23.setItemText(25, _translate("AOOR_mode", "170"))
        self.comboBox_23.setItemText(26, _translate("AOOR_mode", "175"))
        self.label_26.setText(_translate("AOOR_mode", "ATRIAL AMPLITUDE(V)"))
        self.comboBox_25.setItemText(1, _translate("AOOR_mode", "1.25"))
        self.comboBox_25.setItemText(2, _translate("AOOR_mode", "2.5"))
        self.comboBox_25.setItemText(3, _translate("AOOR_mode", "3.75"))
        self.comboBox_25.setItemText(4, _translate("AOOR_mode", "5.0"))
        self.label_27.setText(_translate("AOOR_mode", "ATRIAL PULSE WIDTH(ms)"))
        self.label_28.setText(_translate("AOOR_mode", "ACTIVITY THRESHOLD"))
        self.comboBox_26.setItemText(1, _translate("AOOR_mode", "V-LOW"))
        self.comboBox_26.setItemText(2, _translate("AOOR_mode", "LOW"))
        self.comboBox_26.setItemText(3, _translate("AOOR_mode", "MED-LOW"))
        self.comboBox_26.setItemText(4, _translate("AOOR_mode", "MED"))
        self.comboBox_26.setItemText(5, _translate("AOOR_mode", "MED-HIGH"))
        self.comboBox_26.setItemText(6, _translate("AOOR_mode", "HIGH"))
        self.comboBox_26.setItemText(7, _translate("AOOR_mode", "V-HIGH"))
        self.label_29.setText(_translate("AOOR_mode", "REACTION TIME (s)"))
        self.comboBox_27.setItemText(1, _translate("AOOR_mode", "10"))
        self.comboBox_27.setItemText(2, _translate("AOOR_mode", "20"))
        self.comboBox_27.setItemText(3, _translate("AOOR_mode", "30"))
        self.comboBox_27.setItemText(4, _translate("AOOR_mode", "40"))
        self.comboBox_27.setItemText(5, _translate("AOOR_mode", "50"))
        self.label_30.setText(_translate("AOOR_mode", "RESPONSE FACTOR"))
        self.comboBox_28.setItemText(1, _translate("AOOR_mode", "1"))
        self.comboBox_28.setItemText(2, _translate("AOOR_mode", "2"))
        self.comboBox_28.setItemText(3, _translate("AOOR_mode", "3"))
        self.comboBox_28.setItemText(4, _translate("AOOR_mode", "4"))
        self.comboBox_28.setItemText(5, _translate("AOOR_mode", "5"))
        self.comboBox_28.setItemText(6, _translate("AOOR_mode", "6"))
        self.comboBox_28.setItemText(7, _translate("AOOR_mode", "7"))
        self.comboBox_28.setItemText(8, _translate("AOOR_mode", "8"))
        self.comboBox_28.setItemText(9, _translate("AOOR_mode", "9"))
        self.comboBox_28.setItemText(10, _translate("AOOR_mode", "10"))
        self.comboBox_28.setItemText(11, _translate("AOOR_mode", "11"))
        self.comboBox_28.setItemText(12, _translate("AOOR_mode", "12"))
        self.comboBox_28.setItemText(13, _translate("AOOR_mode", "13"))
        self.comboBox_28.setItemText(14, _translate("AOOR_mode", "14"))
        self.comboBox_28.setItemText(15, _translate("AOOR_mode", "15"))
        self.comboBox_28.setItemText(16, _translate("AOOR_mode", "16"))
        self.label_31.setText(_translate("AOOR_mode", "RECOVERY TIME (min)"))
        self.comboBox_29.setItemText(1, _translate("AOOR_mode", "2"))
        self.comboBox_29.setItemText(2, _translate("AOOR_mode", "3"))
        self.comboBox_29.setItemText(3, _translate("AOOR_mode", "4"))
        self.comboBox_29.setItemText(4, _translate("AOOR_mode", "5"))
        self.comboBox_29.setItemText(5, _translate("AOOR_mode", "6"))
        self.comboBox_29.setItemText(6, _translate("AOOR_mode", "7"))
        self.comboBox_29.setItemText(7, _translate("AOOR_mode", "8"))
        self.comboBox_29.setItemText(8, _translate("AOOR_mode", "9"))
        self.comboBox_29.setItemText(9, _translate("AOOR_mode", "10"))
        self.comboBox_29.setItemText(10, _translate("AOOR_mode", "11"))
        self.comboBox_29.setItemText(11, _translate("AOOR_mode", "12"))
        self.comboBox_29.setItemText(12, _translate("AOOR_mode", "13"))
        self.comboBox_29.setItemText(13, _translate("AOOR_mode", "14"))
        self.comboBox_29.setItemText(14, _translate("AOOR_mode", "15"))
        self.comboBox_29.setItemText(15, _translate("AOOR_mode", "16"))
        self.comboBox_24.setItemText(1, _translate("AOOR_mode", "0.05"))
        self.comboBox_24.setItemText(2, _translate("AOOR_mode", "0.1"))
        self.comboBox_24.setItemText(3, _translate("AOOR_mode", "0.2"))
        self.comboBox_24.setItemText(4, _translate("AOOR_mode", "0.3"))
        self.comboBox_24.setItemText(5, _translate("AOOR_mode", "0.4"))
        self.comboBox_24.setItemText(6, _translate("AOOR_mode", "0.5"))
        self.comboBox_24.setItemText(7, _translate("AOOR_mode", "0.6"))
        self.comboBox_24.setItemText(8, _translate("AOOR_mode", "0.7"))
        self.comboBox_24.setItemText(9, _translate("AOOR_mode", "0.8"))
        self.comboBox_24.setItemText(10, _translate("AOOR_mode", "0.9"))
        self.comboBox_24.setItemText(11, _translate("AOOR_mode", "1.0"))
        self.comboBox_24.setItemText(12, _translate("AOOR_mode", "1.1"))
        self.comboBox_24.setItemText(13, _translate("AOOR_mode", "1.2"))
        self.comboBox_24.setItemText(14, _translate("AOOR_mode", "1.3"))
        self.comboBox_24.setItemText(15, _translate("AOOR_mode", "1.4"))
        self.comboBox_24.setItemText(16, _translate("AOOR_mode", "1.5"))
        self.comboBox_24.setItemText(17, _translate("AOOR_mode", "1.6"))
        self.comboBox_24.setItemText(18, _translate("AOOR_mode", "1.7"))
        self.comboBox_24.setItemText(19, _translate("AOOR_mode", "1.8"))
        self.comboBox_24.setItemText(20, _translate("AOOR_mode", "1.9"))
        self.pushButton_2.setText(_translate("AOOR_mode", "Back"))
        self.pushButton.setText(_translate("AOOR_mode", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AOOR_mode = QtWidgets.QDialog()
    ui = Ui_AOOR_mode()
    ui.setupUi(AOOR_mode)
    AOOR_mode.show()
    sys.exit(app.exec_())
