# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\New folder\AAI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AAI_mode(object):
    def setupUi(self, AAI_mode):
        AAI_mode.setObjectName("AAI_mode")
        AAI_mode.resize(700, 401)
        AAI_mode.setSizeGripEnabled(True)
        self.label_2 = QtWidgets.QLabel(AAI_mode)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(AAI_mode)
        self.label.setGeometry(QtCore.QRect(40, 20, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(AAI_mode)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 350, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(AAI_mode)
        self.pushButton.setGeometry(QtCore.QRect(450, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.formLayoutWidget = QtWidgets.QWidget(AAI_mode)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 110, 351, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_10 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.setItemText(0, "")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_10)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.comboBox_14 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.setItemText(0, "")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_14)
        self.label_86 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_86)
        self.comboBox_83 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_83.setObjectName("comboBox_83")
        self.comboBox_83.addItem("")
        self.comboBox_83.setItemText(0, "")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.comboBox_83.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_83)
        self.label_85 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_85)
        self.comboBox_84 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_84.setObjectName("comboBox_84")
        self.comboBox_84.addItem("")
        self.comboBox_84.setItemText(0, "")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.comboBox_84.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_84)

        self.retranslateUi(AAI_mode)
        QtCore.QMetaObject.connectSlotsByName(AAI_mode)

    def retranslateUi(self, AAI_mode):
        _translate = QtCore.QCoreApplication.translate
        AAI_mode.setWindowTitle(_translate("AAI_mode", "AAI Parameter Change"))
        self.label_2.setText(_translate("AAI_mode", "View and Change your parameters"))
        self.label.setText(_translate("AAI_mode", "Mode:AAI"))
        self.pushButton_2.setText(_translate("AAI_mode", "Back"))
        self.pushButton.setText(_translate("AAI_mode", "Confirm"))
        self.label_3.setText(_translate("AAI_mode", "LOWER RATE LIMIT(PPM)"))
        self.comboBox_5.setItemText(1, _translate("AAI_mode", "30"))
        self.comboBox_5.setItemText(2, _translate("AAI_mode", "35"))
        self.comboBox_5.setItemText(3, _translate("AAI_mode", "40"))
        self.comboBox_5.setItemText(4, _translate("AAI_mode", "45"))
        self.comboBox_5.setItemText(5, _translate("AAI_mode", "50"))
        self.comboBox_5.setItemText(6, _translate("AAI_mode", "51"))
        self.comboBox_5.setItemText(7, _translate("AAI_mode", "52"))
        self.comboBox_5.setItemText(8, _translate("AAI_mode", "53"))
        self.comboBox_5.setItemText(9, _translate("AAI_mode", "54"))
        self.comboBox_5.setItemText(10, _translate("AAI_mode", "55"))
        self.comboBox_5.setItemText(11, _translate("AAI_mode", "56"))
        self.comboBox_5.setItemText(12, _translate("AAI_mode", "57"))
        self.comboBox_5.setItemText(13, _translate("AAI_mode", "58"))
        self.comboBox_5.setItemText(14, _translate("AAI_mode", "59"))
        self.comboBox_5.setItemText(15, _translate("AAI_mode", "60"))
        self.comboBox_5.setItemText(16, _translate("AAI_mode", "61"))
        self.comboBox_5.setItemText(17, _translate("AAI_mode", "62"))
        self.comboBox_5.setItemText(18, _translate("AAI_mode", "63"))
        self.comboBox_5.setItemText(19, _translate("AAI_mode", "64"))
        self.comboBox_5.setItemText(20, _translate("AAI_mode", "65"))
        self.comboBox_5.setItemText(21, _translate("AAI_mode", "66"))
        self.comboBox_5.setItemText(22, _translate("AAI_mode", "67"))
        self.comboBox_5.setItemText(23, _translate("AAI_mode", "68"))
        self.comboBox_5.setItemText(24, _translate("AAI_mode", "69"))
        self.comboBox_5.setItemText(25, _translate("AAI_mode", "70"))
        self.comboBox_5.setItemText(26, _translate("AAI_mode", "71"))
        self.comboBox_5.setItemText(27, _translate("AAI_mode", "72"))
        self.comboBox_5.setItemText(28, _translate("AAI_mode", "73"))
        self.comboBox_5.setItemText(29, _translate("AAI_mode", "74"))
        self.comboBox_5.setItemText(30, _translate("AAI_mode", "75"))
        self.comboBox_5.setItemText(31, _translate("AAI_mode", "76"))
        self.comboBox_5.setItemText(32, _translate("AAI_mode", "77"))
        self.comboBox_5.setItemText(33, _translate("AAI_mode", "78"))
        self.comboBox_5.setItemText(34, _translate("AAI_mode", "79"))
        self.comboBox_5.setItemText(35, _translate("AAI_mode", "80"))
        self.comboBox_5.setItemText(36, _translate("AAI_mode", "81"))
        self.comboBox_5.setItemText(37, _translate("AAI_mode", "82"))
        self.comboBox_5.setItemText(38, _translate("AAI_mode", "83"))
        self.comboBox_5.setItemText(39, _translate("AAI_mode", "84"))
        self.comboBox_5.setItemText(40, _translate("AAI_mode", "85"))
        self.comboBox_5.setItemText(41, _translate("AAI_mode", "86"))
        self.comboBox_5.setItemText(42, _translate("AAI_mode", "87"))
        self.comboBox_5.setItemText(43, _translate("AAI_mode", "88"))
        self.comboBox_5.setItemText(44, _translate("AAI_mode", "89"))
        self.comboBox_5.setItemText(45, _translate("AAI_mode", "90"))
        self.comboBox_5.setItemText(46, _translate("AAI_mode", "95"))
        self.comboBox_5.setItemText(47, _translate("AAI_mode", "100"))
        self.comboBox_5.setItemText(48, _translate("AAI_mode", "105"))
        self.comboBox_5.setItemText(49, _translate("AAI_mode", "110"))
        self.comboBox_5.setItemText(50, _translate("AAI_mode", "115"))
        self.comboBox_5.setItemText(51, _translate("AAI_mode", "120"))
        self.comboBox_5.setItemText(52, _translate("AAI_mode", "125"))
        self.comboBox_5.setItemText(53, _translate("AAI_mode", "130"))
        self.comboBox_5.setItemText(54, _translate("AAI_mode", "135"))
        self.comboBox_5.setItemText(55, _translate("AAI_mode", "140"))
        self.comboBox_5.setItemText(56, _translate("AAI_mode", "145"))
        self.comboBox_5.setItemText(57, _translate("AAI_mode", "150"))
        self.comboBox_5.setItemText(58, _translate("AAI_mode", "155"))
        self.comboBox_5.setItemText(59, _translate("AAI_mode", "160"))
        self.comboBox_5.setItemText(60, _translate("AAI_mode", "165"))
        self.comboBox_5.setItemText(61, _translate("AAI_mode", "170"))
        self.comboBox_5.setItemText(62, _translate("AAI_mode", "175"))
        self.label_4.setText(_translate("AAI_mode", "UPPER RATE LIMIT(PPM)"))
        self.comboBox_4.setItemText(1, _translate("AAI_mode", "50"))
        self.comboBox_4.setItemText(2, _translate("AAI_mode", "55"))
        self.comboBox_4.setItemText(3, _translate("AAI_mode", "60"))
        self.comboBox_4.setItemText(4, _translate("AAI_mode", "65"))
        self.comboBox_4.setItemText(5, _translate("AAI_mode", "70"))
        self.comboBox_4.setItemText(6, _translate("AAI_mode", "75"))
        self.comboBox_4.setItemText(7, _translate("AAI_mode", "80"))
        self.comboBox_4.setItemText(8, _translate("AAI_mode", "85"))
        self.comboBox_4.setItemText(9, _translate("AAI_mode", "90"))
        self.comboBox_4.setItemText(10, _translate("AAI_mode", "95"))
        self.comboBox_4.setItemText(11, _translate("AAI_mode", "100"))
        self.comboBox_4.setItemText(12, _translate("AAI_mode", "105"))
        self.comboBox_4.setItemText(13, _translate("AAI_mode", "110"))
        self.comboBox_4.setItemText(14, _translate("AAI_mode", "115"))
        self.comboBox_4.setItemText(15, _translate("AAI_mode", "120"))
        self.comboBox_4.setItemText(16, _translate("AAI_mode", "125"))
        self.comboBox_4.setItemText(17, _translate("AAI_mode", "130"))
        self.comboBox_4.setItemText(18, _translate("AAI_mode", "135"))
        self.comboBox_4.setItemText(19, _translate("AAI_mode", "140"))
        self.comboBox_4.setItemText(20, _translate("AAI_mode", "145"))
        self.comboBox_4.setItemText(21, _translate("AAI_mode", "150"))
        self.comboBox_4.setItemText(22, _translate("AAI_mode", "155"))
        self.comboBox_4.setItemText(23, _translate("AAI_mode", "160"))
        self.comboBox_4.setItemText(24, _translate("AAI_mode", "165"))
        self.comboBox_4.setItemText(25, _translate("AAI_mode", "170"))
        self.comboBox_4.setItemText(26, _translate("AAI_mode", "175"))
        self.label_5.setText(_translate("AAI_mode", "ATRIAL AMPLITUDE(V)"))
        self.comboBox_3.setItemText(1, _translate("AAI_mode", "1.25"))
        self.comboBox_3.setItemText(2, _translate("AAI_mode", "2.5"))
        self.comboBox_3.setItemText(3, _translate("AAI_mode", "3.75"))
        self.comboBox_3.setItemText(4, _translate("AAI_mode", "5.0"))
        self.label_7.setText(_translate("AAI_mode", "ATRIAL PULSE WIDTH(ms)"))
        self.comboBox_2.setItemText(1, _translate("AAI_mode", "0.05"))
        self.comboBox_2.setItemText(2, _translate("AAI_mode", "0.1"))
        self.comboBox_2.setItemText(3, _translate("AAI_mode", "0.2"))
        self.comboBox_2.setItemText(4, _translate("AAI_mode", "0.3"))
        self.comboBox_2.setItemText(5, _translate("AAI_mode", "0.4"))
        self.comboBox_2.setItemText(6, _translate("AAI_mode", "0.5"))
        self.comboBox_2.setItemText(7, _translate("AAI_mode", "0.6"))
        self.comboBox_2.setItemText(8, _translate("AAI_mode", "0.7"))
        self.comboBox_2.setItemText(9, _translate("AAI_mode", "0.8"))
        self.comboBox_2.setItemText(10, _translate("AAI_mode", "0.9"))
        self.comboBox_2.setItemText(11, _translate("AAI_mode", "1.0"))
        self.comboBox_2.setItemText(12, _translate("AAI_mode", "1.1"))
        self.comboBox_2.setItemText(13, _translate("AAI_mode", "1.2"))
        self.comboBox_2.setItemText(14, _translate("AAI_mode", "1.3"))
        self.comboBox_2.setItemText(15, _translate("AAI_mode", "1.4"))
        self.comboBox_2.setItemText(16, _translate("AAI_mode", "1.5"))
        self.comboBox_2.setItemText(17, _translate("AAI_mode", "1.6"))
        self.comboBox_2.setItemText(18, _translate("AAI_mode", "1.7"))
        self.comboBox_2.setItemText(19, _translate("AAI_mode", "1.8"))
        self.comboBox_2.setItemText(20, _translate("AAI_mode", "1.9"))
        self.label_12.setText(_translate("AAI_mode", "ATRIAL SENSITIVITY (mV)"))
        self.comboBox_10.setItemText(1, _translate("AAI_mode", "0.25"))
        self.comboBox_10.setItemText(2, _translate("AAI_mode", "0.5"))
        self.comboBox_10.setItemText(3, _translate("AAI_mode", "0.75"))
        self.comboBox_10.setItemText(4, _translate("AAI_mode", "1.0"))
        self.comboBox_10.setItemText(5, _translate("AAI_mode", "1.5"))
        self.comboBox_10.setItemText(6, _translate("AAI_mode", "2.0"))
        self.comboBox_10.setItemText(7, _translate("AAI_mode", "2.5"))
        self.comboBox_10.setItemText(8, _translate("AAI_mode", "3.0"))
        self.comboBox_10.setItemText(9, _translate("AAI_mode", "3.5"))
        self.comboBox_10.setItemText(10, _translate("AAI_mode", "4.0"))
        self.comboBox_10.setItemText(11, _translate("AAI_mode", "4.5"))
        self.comboBox_10.setItemText(12, _translate("AAI_mode", "5.0"))
        self.comboBox_10.setItemText(13, _translate("AAI_mode", "5.5"))
        self.comboBox_10.setItemText(14, _translate("AAI_mode", "6.0"))
        self.comboBox_10.setItemText(15, _translate("AAI_mode", "6.5"))
        self.comboBox_10.setItemText(16, _translate("AAI_mode", "7.0"))
        self.comboBox_10.setItemText(17, _translate("AAI_mode", "7.5"))
        self.comboBox_10.setItemText(18, _translate("AAI_mode", "8.0"))
        self.comboBox_10.setItemText(19, _translate("AAI_mode", "8.5"))
        self.comboBox_10.setItemText(20, _translate("AAI_mode", "9.0"))
        self.comboBox_10.setItemText(21, _translate("AAI_mode", "9.5"))
        self.comboBox_10.setItemText(22, _translate("AAI_mode", "10.0"))
        self.label_9.setText(_translate("AAI_mode", "ARP(ms)"))
        self.comboBox.setItemText(1, _translate("AAI_mode", "150"))
        self.comboBox.setItemText(2, _translate("AAI_mode", "160"))
        self.comboBox.setItemText(3, _translate("AAI_mode", "170"))
        self.comboBox.setItemText(4, _translate("AAI_mode", "180"))
        self.comboBox.setItemText(5, _translate("AAI_mode", "190"))
        self.comboBox.setItemText(6, _translate("AAI_mode", "200"))
        self.comboBox.setItemText(7, _translate("AAI_mode", "210"))
        self.comboBox.setItemText(8, _translate("AAI_mode", "220"))
        self.comboBox.setItemText(9, _translate("AAI_mode", "230"))
        self.comboBox.setItemText(10, _translate("AAI_mode", "240"))
        self.comboBox.setItemText(11, _translate("AAI_mode", "250"))
        self.comboBox.setItemText(12, _translate("AAI_mode", "260"))
        self.comboBox.setItemText(13, _translate("AAI_mode", "270"))
        self.comboBox.setItemText(14, _translate("AAI_mode", "280"))
        self.comboBox.setItemText(15, _translate("AAI_mode", "290"))
        self.comboBox.setItemText(16, _translate("AAI_mode", "300"))
        self.comboBox.setItemText(17, _translate("AAI_mode", "310"))
        self.comboBox.setItemText(18, _translate("AAI_mode", "320"))
        self.comboBox.setItemText(19, _translate("AAI_mode", "330"))
        self.comboBox.setItemText(20, _translate("AAI_mode", "340"))
        self.comboBox.setItemText(21, _translate("AAI_mode", "350"))
        self.comboBox.setItemText(22, _translate("AAI_mode", "360"))
        self.comboBox.setItemText(23, _translate("AAI_mode", "370"))
        self.comboBox.setItemText(24, _translate("AAI_mode", "380"))
        self.comboBox.setItemText(25, _translate("AAI_mode", "390"))
        self.comboBox.setItemText(26, _translate("AAI_mode", "400"))
        self.comboBox.setItemText(27, _translate("AAI_mode", "410"))
        self.comboBox.setItemText(28, _translate("AAI_mode", "420"))
        self.comboBox.setItemText(29, _translate("AAI_mode", "430"))
        self.comboBox.setItemText(30, _translate("AAI_mode", "440"))
        self.comboBox.setItemText(31, _translate("AAI_mode", "450"))
        self.comboBox.setItemText(32, _translate("AAI_mode", "460"))
        self.comboBox.setItemText(33, _translate("AAI_mode", "470"))
        self.comboBox.setItemText(34, _translate("AAI_mode", "480"))
        self.comboBox.setItemText(35, _translate("AAI_mode", "490"))
        self.comboBox.setItemText(36, _translate("AAI_mode", "500"))
        self.label_16.setText(_translate("AAI_mode", "PVARP (ms)"))
        self.comboBox_14.setItemText(1, _translate("AAI_mode", "150"))
        self.comboBox_14.setItemText(2, _translate("AAI_mode", "160"))
        self.comboBox_14.setItemText(3, _translate("AAI_mode", "170"))
        self.comboBox_14.setItemText(4, _translate("AAI_mode", "180"))
        self.comboBox_14.setItemText(5, _translate("AAI_mode", "190"))
        self.comboBox_14.setItemText(6, _translate("AAI_mode", "200"))
        self.comboBox_14.setItemText(7, _translate("AAI_mode", "210"))
        self.comboBox_14.setItemText(8, _translate("AAI_mode", "220"))
        self.comboBox_14.setItemText(9, _translate("AAI_mode", "230"))
        self.comboBox_14.setItemText(10, _translate("AAI_mode", "240"))
        self.comboBox_14.setItemText(11, _translate("AAI_mode", "250"))
        self.comboBox_14.setItemText(12, _translate("AAI_mode", "260"))
        self.comboBox_14.setItemText(13, _translate("AAI_mode", "270"))
        self.comboBox_14.setItemText(14, _translate("AAI_mode", "280"))
        self.comboBox_14.setItemText(15, _translate("AAI_mode", "290"))
        self.comboBox_14.setItemText(16, _translate("AAI_mode", "300"))
        self.comboBox_14.setItemText(17, _translate("AAI_mode", "310"))
        self.comboBox_14.setItemText(18, _translate("AAI_mode", "320"))
        self.comboBox_14.setItemText(19, _translate("AAI_mode", "330"))
        self.comboBox_14.setItemText(20, _translate("AAI_mode", "340"))
        self.comboBox_14.setItemText(21, _translate("AAI_mode", "350"))
        self.comboBox_14.setItemText(22, _translate("AAI_mode", "360"))
        self.comboBox_14.setItemText(23, _translate("AAI_mode", "370"))
        self.comboBox_14.setItemText(24, _translate("AAI_mode", "380"))
        self.comboBox_14.setItemText(25, _translate("AAI_mode", "390"))
        self.comboBox_14.setItemText(26, _translate("AAI_mode", "400"))
        self.comboBox_14.setItemText(27, _translate("AAI_mode", "410"))
        self.comboBox_14.setItemText(28, _translate("AAI_mode", "420"))
        self.comboBox_14.setItemText(29, _translate("AAI_mode", "430"))
        self.comboBox_14.setItemText(30, _translate("AAI_mode", "440"))
        self.comboBox_14.setItemText(31, _translate("AAI_mode", "450"))
        self.comboBox_14.setItemText(32, _translate("AAI_mode", "460"))
        self.comboBox_14.setItemText(33, _translate("AAI_mode", "470"))
        self.comboBox_14.setItemText(34, _translate("AAI_mode", "480"))
        self.comboBox_14.setItemText(35, _translate("AAI_mode", "490"))
        self.comboBox_14.setItemText(36, _translate("AAI_mode", "500"))
        self.label_86.setText(_translate("AAI_mode", "HYSTERESIS"))
        self.comboBox_83.setItemText(1, _translate("AAI_mode", "OFF"))
        self.comboBox_83.setItemText(2, _translate("AAI_mode", "30"))
        self.comboBox_83.setItemText(3, _translate("AAI_mode", "35"))
        self.comboBox_83.setItemText(4, _translate("AAI_mode", "40"))
        self.comboBox_83.setItemText(5, _translate("AAI_mode", "45"))
        self.comboBox_83.setItemText(6, _translate("AAI_mode", "50"))
        self.comboBox_83.setItemText(7, _translate("AAI_mode", "51"))
        self.comboBox_83.setItemText(8, _translate("AAI_mode", "52"))
        self.comboBox_83.setItemText(9, _translate("AAI_mode", "53"))
        self.comboBox_83.setItemText(10, _translate("AAI_mode", "54"))
        self.comboBox_83.setItemText(11, _translate("AAI_mode", "55"))
        self.comboBox_83.setItemText(12, _translate("AAI_mode", "56"))
        self.comboBox_83.setItemText(13, _translate("AAI_mode", "57"))
        self.comboBox_83.setItemText(14, _translate("AAI_mode", "58"))
        self.comboBox_83.setItemText(15, _translate("AAI_mode", "59"))
        self.comboBox_83.setItemText(16, _translate("AAI_mode", "60"))
        self.comboBox_83.setItemText(17, _translate("AAI_mode", "61"))
        self.comboBox_83.setItemText(18, _translate("AAI_mode", "62"))
        self.comboBox_83.setItemText(19, _translate("AAI_mode", "63"))
        self.comboBox_83.setItemText(20, _translate("AAI_mode", "64"))
        self.comboBox_83.setItemText(21, _translate("AAI_mode", "65"))
        self.comboBox_83.setItemText(22, _translate("AAI_mode", "66"))
        self.comboBox_83.setItemText(23, _translate("AAI_mode", "67"))
        self.comboBox_83.setItemText(24, _translate("AAI_mode", "68"))
        self.comboBox_83.setItemText(25, _translate("AAI_mode", "69"))
        self.comboBox_83.setItemText(26, _translate("AAI_mode", "70"))
        self.comboBox_83.setItemText(27, _translate("AAI_mode", "71"))
        self.comboBox_83.setItemText(28, _translate("AAI_mode", "72"))
        self.comboBox_83.setItemText(29, _translate("AAI_mode", "73"))
        self.comboBox_83.setItemText(30, _translate("AAI_mode", "74"))
        self.comboBox_83.setItemText(31, _translate("AAI_mode", "75"))
        self.comboBox_83.setItemText(32, _translate("AAI_mode", "76"))
        self.comboBox_83.setItemText(33, _translate("AAI_mode", "77"))
        self.comboBox_83.setItemText(34, _translate("AAI_mode", "78"))
        self.comboBox_83.setItemText(35, _translate("AAI_mode", "79"))
        self.comboBox_83.setItemText(36, _translate("AAI_mode", "80"))
        self.comboBox_83.setItemText(37, _translate("AAI_mode", "81"))
        self.comboBox_83.setItemText(38, _translate("AAI_mode", "82"))
        self.comboBox_83.setItemText(39, _translate("AAI_mode", "83"))
        self.comboBox_83.setItemText(40, _translate("AAI_mode", "84"))
        self.comboBox_83.setItemText(41, _translate("AAI_mode", "85"))
        self.comboBox_83.setItemText(42, _translate("AAI_mode", "86"))
        self.comboBox_83.setItemText(43, _translate("AAI_mode", "87"))
        self.comboBox_83.setItemText(44, _translate("AAI_mode", "88"))
        self.comboBox_83.setItemText(45, _translate("AAI_mode", "89"))
        self.comboBox_83.setItemText(46, _translate("AAI_mode", "90"))
        self.comboBox_83.setItemText(47, _translate("AAI_mode", "95"))
        self.comboBox_83.setItemText(48, _translate("AAI_mode", "100"))
        self.comboBox_83.setItemText(49, _translate("AAI_mode", "105"))
        self.comboBox_83.setItemText(50, _translate("AAI_mode", "110"))
        self.comboBox_83.setItemText(51, _translate("AAI_mode", "115"))
        self.comboBox_83.setItemText(52, _translate("AAI_mode", "120"))
        self.comboBox_83.setItemText(53, _translate("AAI_mode", "125"))
        self.comboBox_83.setItemText(54, _translate("AAI_mode", "130"))
        self.comboBox_83.setItemText(55, _translate("AAI_mode", "135"))
        self.comboBox_83.setItemText(56, _translate("AAI_mode", "140"))
        self.comboBox_83.setItemText(57, _translate("AAI_mode", "145"))
        self.comboBox_83.setItemText(58, _translate("AAI_mode", "150"))
        self.comboBox_83.setItemText(59, _translate("AAI_mode", "155"))
        self.comboBox_83.setItemText(60, _translate("AAI_mode", "160"))
        self.comboBox_83.setItemText(61, _translate("AAI_mode", "165"))
        self.comboBox_83.setItemText(62, _translate("AAI_mode", "170"))
        self.comboBox_83.setItemText(63, _translate("AAI_mode", "175"))
        self.label_85.setText(_translate("AAI_mode", "RATE SMOOTHING (%)"))
        self.comboBox_84.setItemText(1, _translate("AAI_mode", "OFF"))
        self.comboBox_84.setItemText(2, _translate("AAI_mode", "3"))
        self.comboBox_84.setItemText(3, _translate("AAI_mode", "6"))
        self.comboBox_84.setItemText(4, _translate("AAI_mode", "9"))
        self.comboBox_84.setItemText(5, _translate("AAI_mode", "12"))
        self.comboBox_84.setItemText(6, _translate("AAI_mode", "15"))
        self.comboBox_84.setItemText(7, _translate("AAI_mode", "18"))
        self.comboBox_84.setItemText(8, _translate("AAI_mode", "21"))
        self.comboBox_84.setItemText(9, _translate("AAI_mode", "25"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AAI_mode = QtWidgets.QDialog()
    ui = Ui_AAI_mode()
    ui.setupUi(AAI_mode)
    AAI_mode.show()
    sys.exit(app.exec_())
