# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\New folder\DDD.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DDD_mode(object):
    def setupUi(self, DDD_mode):
        DDD_mode.setObjectName("DDD_mode")
        DDD_mode.resize(761, 748)
        DDD_mode.setSizeGripEnabled(True)
        self.pushButton_2 = QtWidgets.QPushButton(DDD_mode)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 680, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(DDD_mode)
        self.pushButton.setGeometry(QtCore.QRect(540, 680, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(DDD_mode)
        self.label.setGeometry(QtCore.QRect(40, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(DDD_mode)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 100, 491, 551))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_9 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.setItemText(0, "")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox_8 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(0, "")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_7 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_10 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.setItemText(0, "")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_10)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_11 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.setItemText(0, "")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboBox_12 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.setItemText(0, "")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.comboBox_13 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.setItemText(0, "")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.comboBox_13)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.comboBox_14 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.setItemText(0, "")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.comboBox_14)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.comboBox_15 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.setItemText(0, "")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.comboBox_15)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.comboBox_17 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.setItemText(0, "")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.comboBox_17)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.comboBox_16 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.setItemText(0, "")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.comboBox_16)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.comboBox_18 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.setItemText(0, "")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.comboBox_18)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.comboBox_19 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.setItemText(0, "")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.comboBox_19)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.comboBox_20 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.setItemText(0, "")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.comboBox_20)
        self.Qlabel = QtWidgets.QLabel(DDD_mode)
        self.Qlabel.setGeometry(QtCore.QRect(40, 70, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Qlabel.setFont(font)
        self.Qlabel.setObjectName("Qlabel")

        self.retranslateUi(DDD_mode)
        QtCore.QMetaObject.connectSlotsByName(DDD_mode)

    def retranslateUi(self, DDD_mode):
        _translate = QtCore.QCoreApplication.translate
        DDD_mode.setWindowTitle(_translate("DDD_mode", "DDD parameters change"))
        self.pushButton_2.setText(_translate("DDD_mode", "Back"))
        self.pushButton.setText(_translate("DDD_mode", "Confirm"))
        self.label.setText(_translate("DDD_mode", "Mode:DDD"))
        self.label_3.setText(_translate("DDD_mode", "LOWER RATE LIMIT(PPM)"))
        self.comboBox_5.setItemText(1, _translate("DDD_mode", "30"))
        self.comboBox_5.setItemText(2, _translate("DDD_mode", "35"))
        self.comboBox_5.setItemText(3, _translate("DDD_mode", "40"))
        self.comboBox_5.setItemText(4, _translate("DDD_mode", "45"))
        self.comboBox_5.setItemText(5, _translate("DDD_mode", "50"))
        self.comboBox_5.setItemText(6, _translate("DDD_mode", "51"))
        self.comboBox_5.setItemText(7, _translate("DDD_mode", "52"))
        self.comboBox_5.setItemText(8, _translate("DDD_mode", "53"))
        self.comboBox_5.setItemText(9, _translate("DDD_mode", "54"))
        self.comboBox_5.setItemText(10, _translate("DDD_mode", "55"))
        self.comboBox_5.setItemText(11, _translate("DDD_mode", "56"))
        self.comboBox_5.setItemText(12, _translate("DDD_mode", "57"))
        self.comboBox_5.setItemText(13, _translate("DDD_mode", "58"))
        self.comboBox_5.setItemText(14, _translate("DDD_mode", "59"))
        self.comboBox_5.setItemText(15, _translate("DDD_mode", "60"))
        self.comboBox_5.setItemText(16, _translate("DDD_mode", "61"))
        self.comboBox_5.setItemText(17, _translate("DDD_mode", "62"))
        self.comboBox_5.setItemText(18, _translate("DDD_mode", "63"))
        self.comboBox_5.setItemText(19, _translate("DDD_mode", "64"))
        self.comboBox_5.setItemText(20, _translate("DDD_mode", "65"))
        self.comboBox_5.setItemText(21, _translate("DDD_mode", "66"))
        self.comboBox_5.setItemText(22, _translate("DDD_mode", "67"))
        self.comboBox_5.setItemText(23, _translate("DDD_mode", "68"))
        self.comboBox_5.setItemText(24, _translate("DDD_mode", "69"))
        self.comboBox_5.setItemText(25, _translate("DDD_mode", "70"))
        self.comboBox_5.setItemText(26, _translate("DDD_mode", "71"))
        self.comboBox_5.setItemText(27, _translate("DDD_mode", "72"))
        self.comboBox_5.setItemText(28, _translate("DDD_mode", "73"))
        self.comboBox_5.setItemText(29, _translate("DDD_mode", "74"))
        self.comboBox_5.setItemText(30, _translate("DDD_mode", "75"))
        self.comboBox_5.setItemText(31, _translate("DDD_mode", "76"))
        self.comboBox_5.setItemText(32, _translate("DDD_mode", "77"))
        self.comboBox_5.setItemText(33, _translate("DDD_mode", "78"))
        self.comboBox_5.setItemText(34, _translate("DDD_mode", "79"))
        self.comboBox_5.setItemText(35, _translate("DDD_mode", "80"))
        self.comboBox_5.setItemText(36, _translate("DDD_mode", "81"))
        self.comboBox_5.setItemText(37, _translate("DDD_mode", "82"))
        self.comboBox_5.setItemText(38, _translate("DDD_mode", "83"))
        self.comboBox_5.setItemText(39, _translate("DDD_mode", "84"))
        self.comboBox_5.setItemText(40, _translate("DDD_mode", "85"))
        self.comboBox_5.setItemText(41, _translate("DDD_mode", "86"))
        self.comboBox_5.setItemText(42, _translate("DDD_mode", "87"))
        self.comboBox_5.setItemText(43, _translate("DDD_mode", "88"))
        self.comboBox_5.setItemText(44, _translate("DDD_mode", "89"))
        self.comboBox_5.setItemText(45, _translate("DDD_mode", "90"))
        self.comboBox_5.setItemText(46, _translate("DDD_mode", "95"))
        self.comboBox_5.setItemText(47, _translate("DDD_mode", "100"))
        self.comboBox_5.setItemText(48, _translate("DDD_mode", "105"))
        self.comboBox_5.setItemText(49, _translate("DDD_mode", "110"))
        self.comboBox_5.setItemText(50, _translate("DDD_mode", "115"))
        self.comboBox_5.setItemText(51, _translate("DDD_mode", "120"))
        self.comboBox_5.setItemText(52, _translate("DDD_mode", "125"))
        self.comboBox_5.setItemText(53, _translate("DDD_mode", "130"))
        self.comboBox_5.setItemText(54, _translate("DDD_mode", "135"))
        self.comboBox_5.setItemText(55, _translate("DDD_mode", "140"))
        self.comboBox_5.setItemText(56, _translate("DDD_mode", "145"))
        self.comboBox_5.setItemText(57, _translate("DDD_mode", "150"))
        self.comboBox_5.setItemText(58, _translate("DDD_mode", "155"))
        self.comboBox_5.setItemText(59, _translate("DDD_mode", "160"))
        self.comboBox_5.setItemText(60, _translate("DDD_mode", "165"))
        self.comboBox_5.setItemText(61, _translate("DDD_mode", "170"))
        self.comboBox_5.setItemText(62, _translate("DDD_mode", "175"))
        self.label_4.setText(_translate("DDD_mode", "UPPER RATE LIMIT(PPM)"))
        self.comboBox_4.setItemText(1, _translate("DDD_mode", "50"))
        self.comboBox_4.setItemText(2, _translate("DDD_mode", "55"))
        self.comboBox_4.setItemText(3, _translate("DDD_mode", "60"))
        self.comboBox_4.setItemText(4, _translate("DDD_mode", "65"))
        self.comboBox_4.setItemText(5, _translate("DDD_mode", "70"))
        self.comboBox_4.setItemText(6, _translate("DDD_mode", "75"))
        self.comboBox_4.setItemText(7, _translate("DDD_mode", "80"))
        self.comboBox_4.setItemText(8, _translate("DDD_mode", "85"))
        self.comboBox_4.setItemText(9, _translate("DDD_mode", "90"))
        self.comboBox_4.setItemText(10, _translate("DDD_mode", "95"))
        self.comboBox_4.setItemText(11, _translate("DDD_mode", "100"))
        self.comboBox_4.setItemText(12, _translate("DDD_mode", "105"))
        self.comboBox_4.setItemText(13, _translate("DDD_mode", "110"))
        self.comboBox_4.setItemText(14, _translate("DDD_mode", "115"))
        self.comboBox_4.setItemText(15, _translate("DDD_mode", "120"))
        self.comboBox_4.setItemText(16, _translate("DDD_mode", "125"))
        self.comboBox_4.setItemText(17, _translate("DDD_mode", "130"))
        self.comboBox_4.setItemText(18, _translate("DDD_mode", "135"))
        self.comboBox_4.setItemText(19, _translate("DDD_mode", "140"))
        self.comboBox_4.setItemText(20, _translate("DDD_mode", "145"))
        self.comboBox_4.setItemText(21, _translate("DDD_mode", "150"))
        self.comboBox_4.setItemText(22, _translate("DDD_mode", "155"))
        self.comboBox_4.setItemText(23, _translate("DDD_mode", "160"))
        self.comboBox_4.setItemText(24, _translate("DDD_mode", "165"))
        self.comboBox_4.setItemText(25, _translate("DDD_mode", "170"))
        self.comboBox_4.setItemText(26, _translate("DDD_mode", "175"))
        self.label_5.setText(_translate("DDD_mode", "FIXED AV DELAY(ms)"))
        self.comboBox_3.setItemText(1, _translate("DDD_mode", "70"))
        self.comboBox_3.setItemText(2, _translate("DDD_mode", "80"))
        self.comboBox_3.setItemText(3, _translate("DDD_mode", "90"))
        self.comboBox_3.setItemText(4, _translate("DDD_mode", "100"))
        self.comboBox_3.setItemText(5, _translate("DDD_mode", "110"))
        self.comboBox_3.setItemText(6, _translate("DDD_mode", "120"))
        self.comboBox_3.setItemText(7, _translate("DDD_mode", "130"))
        self.comboBox_3.setItemText(8, _translate("DDD_mode", "140"))
        self.comboBox_3.setItemText(9, _translate("DDD_mode", "150"))
        self.comboBox_3.setItemText(10, _translate("DDD_mode", "160"))
        self.comboBox_3.setItemText(11, _translate("DDD_mode", "170"))
        self.comboBox_3.setItemText(12, _translate("DDD_mode", "180"))
        self.comboBox_3.setItemText(13, _translate("DDD_mode", "190"))
        self.comboBox_3.setItemText(14, _translate("DDD_mode", "200"))
        self.comboBox_3.setItemText(15, _translate("DDD_mode", "210"))
        self.comboBox_3.setItemText(16, _translate("DDD_mode", "220"))
        self.comboBox_3.setItemText(17, _translate("DDD_mode", "230"))
        self.comboBox_3.setItemText(18, _translate("DDD_mode", "240"))
        self.comboBox_3.setItemText(19, _translate("DDD_mode", "250"))
        self.comboBox_3.setItemText(20, _translate("DDD_mode", "260"))
        self.comboBox_3.setItemText(21, _translate("DDD_mode", "270"))
        self.comboBox_3.setItemText(22, _translate("DDD_mode", "280"))
        self.comboBox_3.setItemText(23, _translate("DDD_mode", "290"))
        self.comboBox_3.setItemText(24, _translate("DDD_mode", "300"))
        self.label_10.setText(_translate("DDD_mode", "DYNAMIC AV DELAY"))
        self.comboBox.setItemText(1, _translate("DDD_mode", "ON"))
        self.comboBox.setItemText(2, _translate("DDD_mode", "OFF"))
        self.label_11.setText(_translate("DDD_mode", "SENSED AV DELAY OFFSET(ms)"))
        self.comboBox_9.setItemText(1, _translate("DDD_mode", "OFF"))
        self.comboBox_9.setItemText(2, _translate("DDD_mode", "-10"))
        self.comboBox_9.setItemText(3, _translate("DDD_mode", "-20"))
        self.comboBox_9.setItemText(4, _translate("DDD_mode", "-30"))
        self.comboBox_9.setItemText(5, _translate("DDD_mode", "-40"))
        self.comboBox_9.setItemText(6, _translate("DDD_mode", "-50"))
        self.comboBox_9.setItemText(7, _translate("DDD_mode", "-60"))
        self.comboBox_9.setItemText(8, _translate("DDD_mode", "-70"))
        self.comboBox_9.setItemText(9, _translate("DDD_mode", "-80"))
        self.comboBox_9.setItemText(10, _translate("DDD_mode", "-90"))
        self.comboBox_9.setItemText(11, _translate("DDD_mode", "-100"))
        self.label_6.setText(_translate("DDD_mode", "ATRIAL AMPLITUDE(V)"))
        self.comboBox_6.setItemText(1, _translate("DDD_mode", "1.25"))
        self.comboBox_6.setItemText(2, _translate("DDD_mode", "2.5"))
        self.comboBox_6.setItemText(3, _translate("DDD_mode", "3.75"))
        self.comboBox_6.setItemText(4, _translate("DDD_mode", "5.0"))
        self.label_9.setText(_translate("DDD_mode", "VENTRICULAR AMPLITUDE(V)"))
        self.comboBox_8.setItemText(1, _translate("DDD_mode", "1.25"))
        self.comboBox_8.setItemText(2, _translate("DDD_mode", "2.5"))
        self.comboBox_8.setItemText(3, _translate("DDD_mode", "3.75"))
        self.comboBox_8.setItemText(4, _translate("DDD_mode", "5.0"))
        self.label_7.setText(_translate("DDD_mode", "ATRIAL PULSE WIDTH(ms)"))
        self.comboBox_7.setItemText(1, _translate("DDD_mode", "0.05"))
        self.comboBox_7.setItemText(2, _translate("DDD_mode", "0.1"))
        self.comboBox_7.setItemText(3, _translate("DDD_mode", "0.2"))
        self.comboBox_7.setItemText(4, _translate("DDD_mode", "0.3"))
        self.comboBox_7.setItemText(5, _translate("DDD_mode", "0.4"))
        self.comboBox_7.setItemText(6, _translate("DDD_mode", "0.5"))
        self.comboBox_7.setItemText(7, _translate("DDD_mode", "0.6"))
        self.comboBox_7.setItemText(8, _translate("DDD_mode", "0.7"))
        self.comboBox_7.setItemText(9, _translate("DDD_mode", "0.8"))
        self.comboBox_7.setItemText(10, _translate("DDD_mode", "0.9"))
        self.comboBox_7.setItemText(11, _translate("DDD_mode", "1.0"))
        self.comboBox_7.setItemText(12, _translate("DDD_mode", "1.1"))
        self.comboBox_7.setItemText(13, _translate("DDD_mode", "1.2"))
        self.comboBox_7.setItemText(14, _translate("DDD_mode", "1.3"))
        self.comboBox_7.setItemText(15, _translate("DDD_mode", "1.4"))
        self.comboBox_7.setItemText(16, _translate("DDD_mode", "1.5"))
        self.comboBox_7.setItemText(17, _translate("DDD_mode", "1.6"))
        self.comboBox_7.setItemText(18, _translate("DDD_mode", "1.7"))
        self.comboBox_7.setItemText(19, _translate("DDD_mode", "1.8"))
        self.comboBox_7.setItemText(20, _translate("DDD_mode", "1.9"))
        self.label_8.setText(_translate("DDD_mode", "VENTRICULAR PULSE WIDTH(ms)"))
        self.comboBox_2.setItemText(1, _translate("DDD_mode", "0.05"))
        self.comboBox_2.setItemText(2, _translate("DDD_mode", "0.1"))
        self.comboBox_2.setItemText(3, _translate("DDD_mode", "0.2"))
        self.comboBox_2.setItemText(4, _translate("DDD_mode", "0.3"))
        self.comboBox_2.setItemText(5, _translate("DDD_mode", "0.4"))
        self.comboBox_2.setItemText(6, _translate("DDD_mode", "0.5"))
        self.comboBox_2.setItemText(7, _translate("DDD_mode", "0.6"))
        self.comboBox_2.setItemText(8, _translate("DDD_mode", "0.7"))
        self.comboBox_2.setItemText(9, _translate("DDD_mode", "0.8"))
        self.comboBox_2.setItemText(10, _translate("DDD_mode", "0.9"))
        self.comboBox_2.setItemText(11, _translate("DDD_mode", "1.0"))
        self.comboBox_2.setItemText(12, _translate("DDD_mode", "1.1"))
        self.comboBox_2.setItemText(13, _translate("DDD_mode", "1.2"))
        self.comboBox_2.setItemText(14, _translate("DDD_mode", "1.3"))
        self.comboBox_2.setItemText(15, _translate("DDD_mode", "1.4"))
        self.comboBox_2.setItemText(16, _translate("DDD_mode", "1.5"))
        self.comboBox_2.setItemText(17, _translate("DDD_mode", "1.6"))
        self.comboBox_2.setItemText(18, _translate("DDD_mode", "1.7"))
        self.comboBox_2.setItemText(19, _translate("DDD_mode", "1.8"))
        self.comboBox_2.setItemText(20, _translate("DDD_mode", "1.9"))
        self.label_12.setText(_translate("DDD_mode", "ATRIAL SENSITIVITY (mV)"))
        self.comboBox_10.setItemText(1, _translate("DDD_mode", "0.25"))
        self.comboBox_10.setItemText(2, _translate("DDD_mode", "0.5"))
        self.comboBox_10.setItemText(3, _translate("DDD_mode", "0.75"))
        self.comboBox_10.setItemText(4, _translate("DDD_mode", "1.0"))
        self.comboBox_10.setItemText(5, _translate("DDD_mode", "1.5"))
        self.comboBox_10.setItemText(6, _translate("DDD_mode", "2.0"))
        self.comboBox_10.setItemText(7, _translate("DDD_mode", "2.5"))
        self.comboBox_10.setItemText(8, _translate("DDD_mode", "3.0"))
        self.comboBox_10.setItemText(9, _translate("DDD_mode", "3.5"))
        self.comboBox_10.setItemText(10, _translate("DDD_mode", "4.0"))
        self.comboBox_10.setItemText(11, _translate("DDD_mode", "4.5"))
        self.comboBox_10.setItemText(12, _translate("DDD_mode", "5.0"))
        self.comboBox_10.setItemText(13, _translate("DDD_mode", "5.5"))
        self.comboBox_10.setItemText(14, _translate("DDD_mode", "6.0"))
        self.comboBox_10.setItemText(15, _translate("DDD_mode", "6.5"))
        self.comboBox_10.setItemText(16, _translate("DDD_mode", "7.0"))
        self.comboBox_10.setItemText(17, _translate("DDD_mode", "7.5"))
        self.comboBox_10.setItemText(18, _translate("DDD_mode", "8.0"))
        self.comboBox_10.setItemText(19, _translate("DDD_mode", "8.5"))
        self.comboBox_10.setItemText(20, _translate("DDD_mode", "9.0"))
        self.comboBox_10.setItemText(21, _translate("DDD_mode", "9.5"))
        self.comboBox_10.setItemText(22, _translate("DDD_mode", "10.0"))
        self.label_13.setText(_translate("DDD_mode", "VENTRICULAR SENSITIVITY (mV)"))
        self.comboBox_11.setItemText(1, _translate("DDD_mode", "0.25"))
        self.comboBox_11.setItemText(2, _translate("DDD_mode", "0.5"))
        self.comboBox_11.setItemText(3, _translate("DDD_mode", "0.75"))
        self.comboBox_11.setItemText(4, _translate("DDD_mode", "1.0"))
        self.comboBox_11.setItemText(5, _translate("DDD_mode", "1.5"))
        self.comboBox_11.setItemText(6, _translate("DDD_mode", "2.0"))
        self.comboBox_11.setItemText(7, _translate("DDD_mode", "2.5"))
        self.comboBox_11.setItemText(8, _translate("DDD_mode", "3.0"))
        self.comboBox_11.setItemText(9, _translate("DDD_mode", "3.5"))
        self.comboBox_11.setItemText(10, _translate("DDD_mode", "4.0"))
        self.comboBox_11.setItemText(11, _translate("DDD_mode", "4.5"))
        self.comboBox_11.setItemText(12, _translate("DDD_mode", "5.0"))
        self.comboBox_11.setItemText(13, _translate("DDD_mode", "5.5"))
        self.comboBox_11.setItemText(14, _translate("DDD_mode", "6.0"))
        self.comboBox_11.setItemText(15, _translate("DDD_mode", "6.5"))
        self.comboBox_11.setItemText(16, _translate("DDD_mode", "7.0"))
        self.comboBox_11.setItemText(17, _translate("DDD_mode", "7.5"))
        self.comboBox_11.setItemText(18, _translate("DDD_mode", "8.0"))
        self.comboBox_11.setItemText(19, _translate("DDD_mode", "8.5"))
        self.comboBox_11.setItemText(20, _translate("DDD_mode", "9.0"))
        self.comboBox_11.setItemText(21, _translate("DDD_mode", "9.5"))
        self.comboBox_11.setItemText(22, _translate("DDD_mode", "10.0"))
        self.label_15.setText(_translate("DDD_mode", "VRP (ms)"))
        self.comboBox_12.setItemText(1, _translate("DDD_mode", "150"))
        self.comboBox_12.setItemText(2, _translate("DDD_mode", "160"))
        self.comboBox_12.setItemText(3, _translate("DDD_mode", "170"))
        self.comboBox_12.setItemText(4, _translate("DDD_mode", "180"))
        self.comboBox_12.setItemText(5, _translate("DDD_mode", "190"))
        self.comboBox_12.setItemText(6, _translate("DDD_mode", "200"))
        self.comboBox_12.setItemText(7, _translate("DDD_mode", "210"))
        self.comboBox_12.setItemText(8, _translate("DDD_mode", "220"))
        self.comboBox_12.setItemText(9, _translate("DDD_mode", "230"))
        self.comboBox_12.setItemText(10, _translate("DDD_mode", "240"))
        self.comboBox_12.setItemText(11, _translate("DDD_mode", "250"))
        self.comboBox_12.setItemText(12, _translate("DDD_mode", "260"))
        self.comboBox_12.setItemText(13, _translate("DDD_mode", "270"))
        self.comboBox_12.setItemText(14, _translate("DDD_mode", "280"))
        self.comboBox_12.setItemText(15, _translate("DDD_mode", "290"))
        self.comboBox_12.setItemText(16, _translate("DDD_mode", "300"))
        self.comboBox_12.setItemText(17, _translate("DDD_mode", "310"))
        self.comboBox_12.setItemText(18, _translate("DDD_mode", "320"))
        self.comboBox_12.setItemText(19, _translate("DDD_mode", "330"))
        self.comboBox_12.setItemText(20, _translate("DDD_mode", "340"))
        self.comboBox_12.setItemText(21, _translate("DDD_mode", "350"))
        self.comboBox_12.setItemText(22, _translate("DDD_mode", "360"))
        self.comboBox_12.setItemText(23, _translate("DDD_mode", "370"))
        self.comboBox_12.setItemText(24, _translate("DDD_mode", "380"))
        self.comboBox_12.setItemText(25, _translate("DDD_mode", "390"))
        self.comboBox_12.setItemText(26, _translate("DDD_mode", "400"))
        self.comboBox_12.setItemText(27, _translate("DDD_mode", "410"))
        self.comboBox_12.setItemText(28, _translate("DDD_mode", "420"))
        self.comboBox_12.setItemText(29, _translate("DDD_mode", "430"))
        self.comboBox_12.setItemText(30, _translate("DDD_mode", "440"))
        self.comboBox_12.setItemText(31, _translate("DDD_mode", "450"))
        self.comboBox_12.setItemText(32, _translate("DDD_mode", "460"))
        self.comboBox_12.setItemText(33, _translate("DDD_mode", "470"))
        self.comboBox_12.setItemText(34, _translate("DDD_mode", "480"))
        self.comboBox_12.setItemText(35, _translate("DDD_mode", "490"))
        self.comboBox_12.setItemText(36, _translate("DDD_mode", "500"))
        self.label_14.setText(_translate("DDD_mode", "ARP (ms)"))
        self.comboBox_13.setItemText(1, _translate("DDD_mode", "150"))
        self.comboBox_13.setItemText(2, _translate("DDD_mode", "160"))
        self.comboBox_13.setItemText(3, _translate("DDD_mode", "170"))
        self.comboBox_13.setItemText(4, _translate("DDD_mode", "180"))
        self.comboBox_13.setItemText(5, _translate("DDD_mode", "190"))
        self.comboBox_13.setItemText(6, _translate("DDD_mode", "200"))
        self.comboBox_13.setItemText(7, _translate("DDD_mode", "210"))
        self.comboBox_13.setItemText(8, _translate("DDD_mode", "220"))
        self.comboBox_13.setItemText(9, _translate("DDD_mode", "230"))
        self.comboBox_13.setItemText(10, _translate("DDD_mode", "240"))
        self.comboBox_13.setItemText(11, _translate("DDD_mode", "250"))
        self.comboBox_13.setItemText(12, _translate("DDD_mode", "260"))
        self.comboBox_13.setItemText(13, _translate("DDD_mode", "270"))
        self.comboBox_13.setItemText(14, _translate("DDD_mode", "280"))
        self.comboBox_13.setItemText(15, _translate("DDD_mode", "290"))
        self.comboBox_13.setItemText(16, _translate("DDD_mode", "300"))
        self.comboBox_13.setItemText(17, _translate("DDD_mode", "310"))
        self.comboBox_13.setItemText(18, _translate("DDD_mode", "320"))
        self.comboBox_13.setItemText(19, _translate("DDD_mode", "330"))
        self.comboBox_13.setItemText(20, _translate("DDD_mode", "340"))
        self.comboBox_13.setItemText(21, _translate("DDD_mode", "350"))
        self.comboBox_13.setItemText(22, _translate("DDD_mode", "360"))
        self.comboBox_13.setItemText(23, _translate("DDD_mode", "370"))
        self.comboBox_13.setItemText(24, _translate("DDD_mode", "380"))
        self.comboBox_13.setItemText(25, _translate("DDD_mode", "390"))
        self.comboBox_13.setItemText(26, _translate("DDD_mode", "400"))
        self.comboBox_13.setItemText(27, _translate("DDD_mode", "410"))
        self.comboBox_13.setItemText(28, _translate("DDD_mode", "420"))
        self.comboBox_13.setItemText(29, _translate("DDD_mode", "430"))
        self.comboBox_13.setItemText(30, _translate("DDD_mode", "440"))
        self.comboBox_13.setItemText(31, _translate("DDD_mode", "450"))
        self.comboBox_13.setItemText(32, _translate("DDD_mode", "460"))
        self.comboBox_13.setItemText(33, _translate("DDD_mode", "470"))
        self.comboBox_13.setItemText(34, _translate("DDD_mode", "480"))
        self.comboBox_13.setItemText(35, _translate("DDD_mode", "490"))
        self.comboBox_13.setItemText(36, _translate("DDD_mode", "500"))
        self.label_16.setText(_translate("DDD_mode", "PVARP (ms)"))
        self.comboBox_14.setItemText(1, _translate("DDD_mode", "150"))
        self.comboBox_14.setItemText(2, _translate("DDD_mode", "160"))
        self.comboBox_14.setItemText(3, _translate("DDD_mode", "170"))
        self.comboBox_14.setItemText(4, _translate("DDD_mode", "180"))
        self.comboBox_14.setItemText(5, _translate("DDD_mode", "190"))
        self.comboBox_14.setItemText(6, _translate("DDD_mode", "200"))
        self.comboBox_14.setItemText(7, _translate("DDD_mode", "210"))
        self.comboBox_14.setItemText(8, _translate("DDD_mode", "220"))
        self.comboBox_14.setItemText(9, _translate("DDD_mode", "230"))
        self.comboBox_14.setItemText(10, _translate("DDD_mode", "240"))
        self.comboBox_14.setItemText(11, _translate("DDD_mode", "250"))
        self.comboBox_14.setItemText(12, _translate("DDD_mode", "260"))
        self.comboBox_14.setItemText(13, _translate("DDD_mode", "270"))
        self.comboBox_14.setItemText(14, _translate("DDD_mode", "280"))
        self.comboBox_14.setItemText(15, _translate("DDD_mode", "290"))
        self.comboBox_14.setItemText(16, _translate("DDD_mode", "300"))
        self.comboBox_14.setItemText(17, _translate("DDD_mode", "310"))
        self.comboBox_14.setItemText(18, _translate("DDD_mode", "320"))
        self.comboBox_14.setItemText(19, _translate("DDD_mode", "330"))
        self.comboBox_14.setItemText(20, _translate("DDD_mode", "340"))
        self.comboBox_14.setItemText(21, _translate("DDD_mode", "350"))
        self.comboBox_14.setItemText(22, _translate("DDD_mode", "360"))
        self.comboBox_14.setItemText(23, _translate("DDD_mode", "370"))
        self.comboBox_14.setItemText(24, _translate("DDD_mode", "380"))
        self.comboBox_14.setItemText(25, _translate("DDD_mode", "390"))
        self.comboBox_14.setItemText(26, _translate("DDD_mode", "400"))
        self.comboBox_14.setItemText(27, _translate("DDD_mode", "410"))
        self.comboBox_14.setItemText(28, _translate("DDD_mode", "420"))
        self.comboBox_14.setItemText(29, _translate("DDD_mode", "430"))
        self.comboBox_14.setItemText(30, _translate("DDD_mode", "440"))
        self.comboBox_14.setItemText(31, _translate("DDD_mode", "450"))
        self.comboBox_14.setItemText(32, _translate("DDD_mode", "460"))
        self.comboBox_14.setItemText(33, _translate("DDD_mode", "470"))
        self.comboBox_14.setItemText(34, _translate("DDD_mode", "480"))
        self.comboBox_14.setItemText(35, _translate("DDD_mode", "490"))
        self.comboBox_14.setItemText(36, _translate("DDD_mode", "500"))
        self.label_17.setText(_translate("DDD_mode", "PVARP EXTENTION (ms)"))
        self.comboBox_15.setItemText(1, _translate("DDD_mode", "OFF"))
        self.comboBox_15.setItemText(2, _translate("DDD_mode", "50"))
        self.comboBox_15.setItemText(3, _translate("DDD_mode", "60"))
        self.comboBox_15.setItemText(4, _translate("DDD_mode", "70"))
        self.comboBox_15.setItemText(5, _translate("DDD_mode", "80"))
        self.comboBox_15.setItemText(6, _translate("DDD_mode", "90"))
        self.comboBox_15.setItemText(7, _translate("DDD_mode", "100"))
        self.comboBox_15.setItemText(8, _translate("DDD_mode", "110"))
        self.comboBox_15.setItemText(9, _translate("DDD_mode", "120"))
        self.comboBox_15.setItemText(10, _translate("DDD_mode", "130"))
        self.comboBox_15.setItemText(11, _translate("DDD_mode", "140"))
        self.comboBox_15.setItemText(12, _translate("DDD_mode", "150"))
        self.comboBox_15.setItemText(13, _translate("DDD_mode", "160"))
        self.comboBox_15.setItemText(14, _translate("DDD_mode", "170"))
        self.comboBox_15.setItemText(15, _translate("DDD_mode", "180"))
        self.comboBox_15.setItemText(16, _translate("DDD_mode", "190"))
        self.comboBox_15.setItemText(17, _translate("DDD_mode", "200"))
        self.comboBox_15.setItemText(18, _translate("DDD_mode", "210"))
        self.comboBox_15.setItemText(19, _translate("DDD_mode", "220"))
        self.comboBox_15.setItemText(20, _translate("DDD_mode", "230"))
        self.comboBox_15.setItemText(21, _translate("DDD_mode", "240"))
        self.comboBox_15.setItemText(22, _translate("DDD_mode", "250"))
        self.comboBox_15.setItemText(23, _translate("DDD_mode", "260"))
        self.comboBox_15.setItemText(24, _translate("DDD_mode", "270"))
        self.comboBox_15.setItemText(25, _translate("DDD_mode", "280"))
        self.comboBox_15.setItemText(26, _translate("DDD_mode", "290"))
        self.comboBox_15.setItemText(27, _translate("DDD_mode", "300"))
        self.comboBox_15.setItemText(28, _translate("DDD_mode", "310"))
        self.comboBox_15.setItemText(29, _translate("DDD_mode", "320"))
        self.comboBox_15.setItemText(30, _translate("DDD_mode", "330"))
        self.comboBox_15.setItemText(31, _translate("DDD_mode", "340"))
        self.comboBox_15.setItemText(32, _translate("DDD_mode", "350"))
        self.comboBox_15.setItemText(33, _translate("DDD_mode", "360"))
        self.comboBox_15.setItemText(34, _translate("DDD_mode", "370"))
        self.comboBox_15.setItemText(35, _translate("DDD_mode", "380"))
        self.comboBox_15.setItemText(36, _translate("DDD_mode", "390"))
        self.comboBox_15.setItemText(37, _translate("DDD_mode", "400"))
        self.label_18.setText(_translate("DDD_mode", "HYSTERESIS"))
        self.comboBox_17.setItemText(1, _translate("DDD_mode", "OFF"))
        self.comboBox_17.setItemText(2, _translate("DDD_mode", "30"))
        self.comboBox_17.setItemText(3, _translate("DDD_mode", "35"))
        self.comboBox_17.setItemText(4, _translate("DDD_mode", "40"))
        self.comboBox_17.setItemText(5, _translate("DDD_mode", "45"))
        self.comboBox_17.setItemText(6, _translate("DDD_mode", "50"))
        self.comboBox_17.setItemText(7, _translate("DDD_mode", "51"))
        self.comboBox_17.setItemText(8, _translate("DDD_mode", "52"))
        self.comboBox_17.setItemText(9, _translate("DDD_mode", "53"))
        self.comboBox_17.setItemText(10, _translate("DDD_mode", "54"))
        self.comboBox_17.setItemText(11, _translate("DDD_mode", "55"))
        self.comboBox_17.setItemText(12, _translate("DDD_mode", "56"))
        self.comboBox_17.setItemText(13, _translate("DDD_mode", "57"))
        self.comboBox_17.setItemText(14, _translate("DDD_mode", "58"))
        self.comboBox_17.setItemText(15, _translate("DDD_mode", "59"))
        self.comboBox_17.setItemText(16, _translate("DDD_mode", "60"))
        self.comboBox_17.setItemText(17, _translate("DDD_mode", "61"))
        self.comboBox_17.setItemText(18, _translate("DDD_mode", "62"))
        self.comboBox_17.setItemText(19, _translate("DDD_mode", "63"))
        self.comboBox_17.setItemText(20, _translate("DDD_mode", "64"))
        self.comboBox_17.setItemText(21, _translate("DDD_mode", "65"))
        self.comboBox_17.setItemText(22, _translate("DDD_mode", "66"))
        self.comboBox_17.setItemText(23, _translate("DDD_mode", "67"))
        self.comboBox_17.setItemText(24, _translate("DDD_mode", "68"))
        self.comboBox_17.setItemText(25, _translate("DDD_mode", "69"))
        self.comboBox_17.setItemText(26, _translate("DDD_mode", "70"))
        self.comboBox_17.setItemText(27, _translate("DDD_mode", "71"))
        self.comboBox_17.setItemText(28, _translate("DDD_mode", "72"))
        self.comboBox_17.setItemText(29, _translate("DDD_mode", "73"))
        self.comboBox_17.setItemText(30, _translate("DDD_mode", "74"))
        self.comboBox_17.setItemText(31, _translate("DDD_mode", "75"))
        self.comboBox_17.setItemText(32, _translate("DDD_mode", "76"))
        self.comboBox_17.setItemText(33, _translate("DDD_mode", "77"))
        self.comboBox_17.setItemText(34, _translate("DDD_mode", "78"))
        self.comboBox_17.setItemText(35, _translate("DDD_mode", "79"))
        self.comboBox_17.setItemText(36, _translate("DDD_mode", "80"))
        self.comboBox_17.setItemText(37, _translate("DDD_mode", "81"))
        self.comboBox_17.setItemText(38, _translate("DDD_mode", "82"))
        self.comboBox_17.setItemText(39, _translate("DDD_mode", "83"))
        self.comboBox_17.setItemText(40, _translate("DDD_mode", "84"))
        self.comboBox_17.setItemText(41, _translate("DDD_mode", "85"))
        self.comboBox_17.setItemText(42, _translate("DDD_mode", "86"))
        self.comboBox_17.setItemText(43, _translate("DDD_mode", "87"))
        self.comboBox_17.setItemText(44, _translate("DDD_mode", "88"))
        self.comboBox_17.setItemText(45, _translate("DDD_mode", "89"))
        self.comboBox_17.setItemText(46, _translate("DDD_mode", "90"))
        self.comboBox_17.setItemText(47, _translate("DDD_mode", "95"))
        self.comboBox_17.setItemText(48, _translate("DDD_mode", "100"))
        self.comboBox_17.setItemText(49, _translate("DDD_mode", "105"))
        self.comboBox_17.setItemText(50, _translate("DDD_mode", "110"))
        self.comboBox_17.setItemText(51, _translate("DDD_mode", "115"))
        self.comboBox_17.setItemText(52, _translate("DDD_mode", "120"))
        self.comboBox_17.setItemText(53, _translate("DDD_mode", "125"))
        self.comboBox_17.setItemText(54, _translate("DDD_mode", "130"))
        self.comboBox_17.setItemText(55, _translate("DDD_mode", "135"))
        self.comboBox_17.setItemText(56, _translate("DDD_mode", "140"))
        self.comboBox_17.setItemText(57, _translate("DDD_mode", "145"))
        self.comboBox_17.setItemText(58, _translate("DDD_mode", "150"))
        self.comboBox_17.setItemText(59, _translate("DDD_mode", "155"))
        self.comboBox_17.setItemText(60, _translate("DDD_mode", "160"))
        self.comboBox_17.setItemText(61, _translate("DDD_mode", "165"))
        self.comboBox_17.setItemText(62, _translate("DDD_mode", "170"))
        self.comboBox_17.setItemText(63, _translate("DDD_mode", "175"))
        self.label_19.setText(_translate("DDD_mode", "RATE SMOOTHING (%)"))
        self.comboBox_16.setItemText(1, _translate("DDD_mode", "OFF"))
        self.comboBox_16.setItemText(2, _translate("DDD_mode", "3"))
        self.comboBox_16.setItemText(3, _translate("DDD_mode", "6"))
        self.comboBox_16.setItemText(4, _translate("DDD_mode", "9"))
        self.comboBox_16.setItemText(5, _translate("DDD_mode", "12"))
        self.comboBox_16.setItemText(6, _translate("DDD_mode", "15"))
        self.comboBox_16.setItemText(7, _translate("DDD_mode", "18"))
        self.comboBox_16.setItemText(8, _translate("DDD_mode", "21"))
        self.comboBox_16.setItemText(9, _translate("DDD_mode", "25"))
        self.label_20.setText(_translate("DDD_mode", "ATR DURATION (cc)"))
        self.comboBox_18.setItemText(1, _translate("DDD_mode", "10"))
        self.comboBox_18.setItemText(2, _translate("DDD_mode", "20"))
        self.comboBox_18.setItemText(3, _translate("DDD_mode", "40"))
        self.comboBox_18.setItemText(4, _translate("DDD_mode", "60"))
        self.comboBox_18.setItemText(5, _translate("DDD_mode", "80"))
        self.comboBox_18.setItemText(6, _translate("DDD_mode", "100"))
        self.comboBox_18.setItemText(7, _translate("DDD_mode", "150"))
        self.comboBox_18.setItemText(8, _translate("DDD_mode", "200"))
        self.comboBox_18.setItemText(9, _translate("DDD_mode", "250"))
        self.comboBox_18.setItemText(10, _translate("DDD_mode", "300"))
        self.comboBox_18.setItemText(11, _translate("DDD_mode", "350"))
        self.comboBox_18.setItemText(12, _translate("DDD_mode", "400"))
        self.comboBox_18.setItemText(13, _translate("DDD_mode", "450"))
        self.comboBox_18.setItemText(14, _translate("DDD_mode", "500"))
        self.comboBox_18.setItemText(15, _translate("DDD_mode", "550"))
        self.comboBox_18.setItemText(16, _translate("DDD_mode", "600"))
        self.comboBox_18.setItemText(17, _translate("DDD_mode", "650"))
        self.comboBox_18.setItemText(18, _translate("DDD_mode", "700"))
        self.comboBox_18.setItemText(19, _translate("DDD_mode", "750"))
        self.comboBox_18.setItemText(20, _translate("DDD_mode", "800"))
        self.comboBox_18.setItemText(21, _translate("DDD_mode", "850"))
        self.comboBox_18.setItemText(22, _translate("DDD_mode", "900"))
        self.comboBox_18.setItemText(23, _translate("DDD_mode", "950"))
        self.comboBox_18.setItemText(24, _translate("DDD_mode", "1000"))
        self.comboBox_18.setItemText(25, _translate("DDD_mode", "1050"))
        self.comboBox_18.setItemText(26, _translate("DDD_mode", "1100"))
        self.comboBox_18.setItemText(27, _translate("DDD_mode", "1150"))
        self.comboBox_18.setItemText(28, _translate("DDD_mode", "1200"))
        self.comboBox_18.setItemText(29, _translate("DDD_mode", "1250"))
        self.comboBox_18.setItemText(30, _translate("DDD_mode", "1300"))
        self.comboBox_18.setItemText(31, _translate("DDD_mode", "1350"))
        self.comboBox_18.setItemText(32, _translate("DDD_mode", "1400"))
        self.comboBox_18.setItemText(33, _translate("DDD_mode", "1450"))
        self.comboBox_18.setItemText(34, _translate("DDD_mode", "1500"))
        self.comboBox_18.setItemText(35, _translate("DDD_mode", "1550"))
        self.comboBox_18.setItemText(36, _translate("DDD_mode", "1600"))
        self.comboBox_18.setItemText(37, _translate("DDD_mode", "1650"))
        self.comboBox_18.setItemText(38, _translate("DDD_mode", "1700"))
        self.comboBox_18.setItemText(39, _translate("DDD_mode", "1750"))
        self.comboBox_18.setItemText(40, _translate("DDD_mode", "1800"))
        self.comboBox_18.setItemText(41, _translate("DDD_mode", "1850"))
        self.comboBox_18.setItemText(42, _translate("DDD_mode", "1900"))
        self.comboBox_18.setItemText(43, _translate("DDD_mode", "1950"))
        self.comboBox_18.setItemText(44, _translate("DDD_mode", "2000"))
        self.label_21.setText(_translate("DDD_mode", "ATR FALLBACK MODE"))
        self.comboBox_19.setItemText(1, _translate("DDD_mode", "ON"))
        self.comboBox_19.setItemText(2, _translate("DDD_mode", "OFF"))
        self.label_22.setText(_translate("DDD_mode", "ATR FALLBACK TIME (min)"))
        self.comboBox_20.setItemText(1, _translate("DDD_mode", "1"))
        self.comboBox_20.setItemText(2, _translate("DDD_mode", "2"))
        self.comboBox_20.setItemText(3, _translate("DDD_mode", "3"))
        self.comboBox_20.setItemText(4, _translate("DDD_mode", "4"))
        self.comboBox_20.setItemText(5, _translate("DDD_mode", "5"))
        self.Qlabel.setText(_translate("DDD_mode", "View and Change your parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DDD_mode = QtWidgets.QDialog()
    ui = Ui_DDD_mode()
    ui.setupUi(DDD_mode)
    DDD_mode.show()
    sys.exit(app.exec_())
