from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DOO_mode(object):
    def setupUi(self, DOO_mode):
        DOO_mode.setObjectName("DOO_mode")
        DOO_mode.resize(700, 401)
        DOO_mode.setSizeGripEnabled(True)
        self.formLayoutWidget = QtWidgets.QWidget(DOO_mode)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 100, 351, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.comboBox_7 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.comboBox_8 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(0, "")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.pushButton = QtWidgets.QPushButton(DOO_mode)
        self.pushButton.setGeometry(QtCore.QRect(430, 340, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(DOO_mode)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 340, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(DOO_mode)
        self.label.setGeometry(QtCore.QRect(20, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Qlabel = QtWidgets.QLabel(DOO_mode)
        self.Qlabel.setGeometry(QtCore.QRect(20, 50, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Qlabel.setFont(font)
        self.Qlabel.setObjectName("Qlabel")

        self.retranslateUi(DOO_mode)
        QtCore.QMetaObject.connectSlotsByName(DOO_mode)

    def retranslateUi(self, DOO_mode):
        _translate = QtCore.QCoreApplication.translate
        DOO_mode.setWindowTitle(_translate("DOO_mode", "DOO Parameter Change"))
        self.label_3.setText(_translate("DOO_mode", "LOWER RATE LIMIT(PPM)"))
        self.comboBox_5.setItemText(1, _translate("DOO_mode", "30"))
        self.comboBox_5.setItemText(2, _translate("DOO_mode", "35"))
        self.comboBox_5.setItemText(3, _translate("DOO_mode", "40"))
        self.comboBox_5.setItemText(4, _translate("DOO_mode", "45"))
        self.comboBox_5.setItemText(5, _translate("DOO_mode", "50"))
        self.comboBox_5.setItemText(6, _translate("DOO_mode", "51"))
        self.comboBox_5.setItemText(7, _translate("DOO_mode", "52"))
        self.comboBox_5.setItemText(8, _translate("DOO_mode", "53"))
        self.comboBox_5.setItemText(9, _translate("DOO_mode", "54"))
        self.comboBox_5.setItemText(10, _translate("DOO_mode", "55"))
        self.comboBox_5.setItemText(11, _translate("DOO_mode", "56"))
        self.comboBox_5.setItemText(12, _translate("DOO_mode", "57"))
        self.comboBox_5.setItemText(13, _translate("DOO_mode", "58"))
        self.comboBox_5.setItemText(14, _translate("DOO_mode", "59"))
        self.comboBox_5.setItemText(15, _translate("DOO_mode", "60"))
        self.comboBox_5.setItemText(16, _translate("DOO_mode", "61"))
        self.comboBox_5.setItemText(17, _translate("DOO_mode", "62"))
        self.comboBox_5.setItemText(18, _translate("DOO_mode", "63"))
        self.comboBox_5.setItemText(19, _translate("DOO_mode", "64"))
        self.comboBox_5.setItemText(20, _translate("DOO_mode", "65"))
        self.comboBox_5.setItemText(21, _translate("DOO_mode", "66"))
        self.comboBox_5.setItemText(22, _translate("DOO_mode", "67"))
        self.comboBox_5.setItemText(23, _translate("DOO_mode", "68"))
        self.comboBox_5.setItemText(24, _translate("DOO_mode", "69"))
        self.comboBox_5.setItemText(25, _translate("DOO_mode", "70"))
        self.comboBox_5.setItemText(26, _translate("DOO_mode", "71"))
        self.comboBox_5.setItemText(27, _translate("DOO_mode", "72"))
        self.comboBox_5.setItemText(28, _translate("DOO_mode", "73"))
        self.comboBox_5.setItemText(29, _translate("DOO_mode", "74"))
        self.comboBox_5.setItemText(30, _translate("DOO_mode", "75"))
        self.comboBox_5.setItemText(31, _translate("DOO_mode", "76"))
        self.comboBox_5.setItemText(32, _translate("DOO_mode", "77"))
        self.comboBox_5.setItemText(33, _translate("DOO_mode", "78"))
        self.comboBox_5.setItemText(34, _translate("DOO_mode", "79"))
        self.comboBox_5.setItemText(35, _translate("DOO_mode", "80"))
        self.comboBox_5.setItemText(36, _translate("DOO_mode", "81"))
        self.comboBox_5.setItemText(37, _translate("DOO_mode", "82"))
        self.comboBox_5.setItemText(38, _translate("DOO_mode", "83"))
        self.comboBox_5.setItemText(39, _translate("DOO_mode", "84"))
        self.comboBox_5.setItemText(40, _translate("DOO_mode", "85"))
        self.comboBox_5.setItemText(41, _translate("DOO_mode", "86"))
        self.comboBox_5.setItemText(42, _translate("DOO_mode", "87"))
        self.comboBox_5.setItemText(43, _translate("DOO_mode", "88"))
        self.comboBox_5.setItemText(44, _translate("DOO_mode", "89"))
        self.comboBox_5.setItemText(45, _translate("DOO_mode", "90"))
        self.comboBox_5.setItemText(46, _translate("DOO_mode", "95"))
        self.comboBox_5.setItemText(47, _translate("DOO_mode", "100"))
        self.comboBox_5.setItemText(48, _translate("DOO_mode", "105"))
        self.comboBox_5.setItemText(49, _translate("DOO_mode", "110"))
        self.comboBox_5.setItemText(50, _translate("DOO_mode", "115"))
        self.comboBox_5.setItemText(51, _translate("DOO_mode", "120"))
        self.comboBox_5.setItemText(52, _translate("DOO_mode", "125"))
        self.comboBox_5.setItemText(53, _translate("DOO_mode", "130"))
        self.comboBox_5.setItemText(54, _translate("DOO_mode", "135"))
        self.comboBox_5.setItemText(55, _translate("DOO_mode", "140"))
        self.comboBox_5.setItemText(56, _translate("DOO_mode", "145"))
        self.comboBox_5.setItemText(57, _translate("DOO_mode", "150"))
        self.comboBox_5.setItemText(58, _translate("DOO_mode", "155"))
        self.comboBox_5.setItemText(59, _translate("DOO_mode", "160"))
        self.comboBox_5.setItemText(60, _translate("DOO_mode", "165"))
        self.comboBox_5.setItemText(61, _translate("DOO_mode", "170"))
        self.comboBox_5.setItemText(62, _translate("DOO_mode", "175"))
        self.label_4.setText(_translate("DOO_mode", "UPPER RATE LIMIT(PPM)"))
        self.comboBox_4.setItemText(1, _translate("DOO_mode", "50"))
        self.comboBox_4.setItemText(2, _translate("DOO_mode", "55"))
        self.comboBox_4.setItemText(3, _translate("DOO_mode", "60"))
        self.comboBox_4.setItemText(4, _translate("DOO_mode", "65"))
        self.comboBox_4.setItemText(5, _translate("DOO_mode", "70"))
        self.comboBox_4.setItemText(6, _translate("DOO_mode", "75"))
        self.comboBox_4.setItemText(7, _translate("DOO_mode", "80"))
        self.comboBox_4.setItemText(8, _translate("DOO_mode", "85"))
        self.comboBox_4.setItemText(9, _translate("DOO_mode", "90"))
        self.comboBox_4.setItemText(10, _translate("DOO_mode", "95"))
        self.comboBox_4.setItemText(11, _translate("DOO_mode", "100"))
        self.comboBox_4.setItemText(12, _translate("DOO_mode", "105"))
        self.comboBox_4.setItemText(13, _translate("DOO_mode", "110"))
        self.comboBox_4.setItemText(14, _translate("DOO_mode", "115"))
        self.comboBox_4.setItemText(15, _translate("DOO_mode", "120"))
        self.comboBox_4.setItemText(16, _translate("DOO_mode", "125"))
        self.comboBox_4.setItemText(17, _translate("DOO_mode", "130"))
        self.comboBox_4.setItemText(18, _translate("DOO_mode", "135"))
        self.comboBox_4.setItemText(19, _translate("DOO_mode", "140"))
        self.comboBox_4.setItemText(20, _translate("DOO_mode", "145"))
        self.comboBox_4.setItemText(21, _translate("DOO_mode", "150"))
        self.comboBox_4.setItemText(22, _translate("DOO_mode", "155"))
        self.comboBox_4.setItemText(23, _translate("DOO_mode", "160"))
        self.comboBox_4.setItemText(24, _translate("DOO_mode", "165"))
        self.comboBox_4.setItemText(25, _translate("DOO_mode", "170"))
        self.comboBox_4.setItemText(26, _translate("DOO_mode", "175"))
        self.label_5.setText(_translate("DOO_mode", "FIXED AV DELAY(ms)"))
        self.comboBox_3.setItemText(1, _translate("DOO_mode", "70"))
        self.comboBox_3.setItemText(2, _translate("DOO_mode", "80"))
        self.comboBox_3.setItemText(3, _translate("DOO_mode", "90"))
        self.comboBox_3.setItemText(4, _translate("DOO_mode", "100"))
        self.comboBox_3.setItemText(5, _translate("DOO_mode", "110"))
        self.comboBox_3.setItemText(6, _translate("DOO_mode", "120"))
        self.comboBox_3.setItemText(7, _translate("DOO_mode", "130"))
        self.comboBox_3.setItemText(8, _translate("DOO_mode", "140"))
        self.comboBox_3.setItemText(9, _translate("DOO_mode", "150"))
        self.comboBox_3.setItemText(10, _translate("DOO_mode", "160"))
        self.comboBox_3.setItemText(11, _translate("DOO_mode", "170"))
        self.comboBox_3.setItemText(12, _translate("DOO_mode", "180"))
        self.comboBox_3.setItemText(13, _translate("DOO_mode", "190"))
        self.comboBox_3.setItemText(14, _translate("DOO_mode", "200"))
        self.comboBox_3.setItemText(15, _translate("DOO_mode", "210"))
        self.comboBox_3.setItemText(16, _translate("DOO_mode", "220"))
        self.comboBox_3.setItemText(17, _translate("DOO_mode", "230"))
        self.comboBox_3.setItemText(18, _translate("DOO_mode", "240"))
        self.comboBox_3.setItemText(19, _translate("DOO_mode", "250"))
        self.comboBox_3.setItemText(20, _translate("DOO_mode", "260"))
        self.comboBox_3.setItemText(21, _translate("DOO_mode", "270"))
        self.comboBox_3.setItemText(22, _translate("DOO_mode", "280"))
        self.comboBox_3.setItemText(23, _translate("DOO_mode", "290"))
        self.comboBox_3.setItemText(24, _translate("DOO_mode", "300"))
        self.label_6.setText(_translate("DOO_mode", "ATRIAL AMPLITUDE(V)"))
        self.comboBox_6.setItemText(1, _translate("DOO_mode", "1.25"))
        self.comboBox_6.setItemText(2, _translate("DOO_mode", "2.5"))
        self.comboBox_6.setItemText(3, _translate("DOO_mode", "3.75"))
        self.comboBox_6.setItemText(4, _translate("DOO_mode", "5.0"))
        self.comboBox_7.setItemText(1, _translate("DOO_mode", "0.05"))
        self.comboBox_7.setItemText(2, _translate("DOO_mode", "0.1"))
        self.comboBox_7.setItemText(3, _translate("DOO_mode", "0.2"))
        self.comboBox_7.setItemText(4, _translate("DOO_mode", "0.3"))
        self.comboBox_7.setItemText(5, _translate("DOO_mode", "0.4"))
        self.comboBox_7.setItemText(6, _translate("DOO_mode", "0.5"))
        self.comboBox_7.setItemText(7, _translate("DOO_mode", "0.6"))
        self.comboBox_7.setItemText(8, _translate("DOO_mode", "0.7"))
        self.comboBox_7.setItemText(9, _translate("DOO_mode", "0.8"))
        self.comboBox_7.setItemText(10, _translate("DOO_mode", "0.9"))
        self.comboBox_7.setItemText(11, _translate("DOO_mode", "1.0"))
        self.comboBox_7.setItemText(12, _translate("DOO_mode", "1.1"))
        self.comboBox_7.setItemText(13, _translate("DOO_mode", "1.2"))
        self.comboBox_7.setItemText(14, _translate("DOO_mode", "1.3"))
        self.comboBox_7.setItemText(15, _translate("DOO_mode", "1.4"))
        self.comboBox_7.setItemText(16, _translate("DOO_mode", "1.5"))
        self.comboBox_7.setItemText(17, _translate("DOO_mode", "1.6"))
        self.comboBox_7.setItemText(18, _translate("DOO_mode", "1.7"))
        self.comboBox_7.setItemText(19, _translate("DOO_mode", "1.8"))
        self.comboBox_7.setItemText(20, _translate("DOO_mode", "1.9"))
        self.comboBox_2.setItemText(1, _translate("DOO_mode", "0.05"))
        self.comboBox_2.setItemText(2, _translate("DOO_mode", "0.1"))
        self.comboBox_2.setItemText(3, _translate("DOO_mode", "0.2"))
        self.comboBox_2.setItemText(4, _translate("DOO_mode", "0.3"))
        self.comboBox_2.setItemText(5, _translate("DOO_mode", "0.4"))
        self.comboBox_2.setItemText(6, _translate("DOO_mode", "0.5"))
        self.comboBox_2.setItemText(7, _translate("DOO_mode", "0.6"))
        self.comboBox_2.setItemText(8, _translate("DOO_mode", "0.7"))
        self.comboBox_2.setItemText(9, _translate("DOO_mode", "0.8"))
        self.comboBox_2.setItemText(10, _translate("DOO_mode", "0.9"))
        self.comboBox_2.setItemText(11, _translate("DOO_mode", "1.0"))
        self.comboBox_2.setItemText(12, _translate("DOO_mode", "1.1"))
        self.comboBox_2.setItemText(13, _translate("DOO_mode", "1.2"))
        self.comboBox_2.setItemText(14, _translate("DOO_mode", "1.3"))
        self.comboBox_2.setItemText(15, _translate("DOO_mode", "1.4"))
        self.comboBox_2.setItemText(16, _translate("DOO_mode", "1.5"))
        self.comboBox_2.setItemText(17, _translate("DOO_mode", "1.6"))
        self.comboBox_2.setItemText(18, _translate("DOO_mode", "1.7"))
        self.comboBox_2.setItemText(19, _translate("DOO_mode", "1.8"))
        self.comboBox_2.setItemText(20, _translate("DOO_mode", "1.9"))
        self.comboBox_8.setItemText(1, _translate("DOO_mode", "1.25"))
        self.comboBox_8.setItemText(2, _translate("DOO_mode", "2.5"))
        self.comboBox_8.setItemText(3, _translate("DOO_mode", "3.75"))
        self.comboBox_8.setItemText(4, _translate("DOO_mode", "5.0"))
        self.label_9.setText(_translate("DOO_mode", "VENTRICULAR AMPLITUDE(V)"))
        self.label_7.setText(_translate("DOO_mode", "ATRIAL PULSE WIDTH(ms)"))
        self.label_8.setText(_translate("DOO_mode", "VENTRICULAR PULSE WIDTH(ms)"))
        self.pushButton.setText(_translate("DOO_mode", "Confirm"))
        self.pushButton_2.setText(_translate("DOO_mode", "Back"))
        self.label.setText(_translate("DOO_mode", "Mode:DOO"))
        self.Qlabel.setText(_translate("DOO_mode", "View and Change your parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DOO_mode = QtWidgets.QDialog()
    ui = Ui_DOO_mode()
    ui.setupUi(DOO_mode)
    DOO_mode.show()
    sys.exit(app.exec_())
