# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\New folder\DOOR.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DOOR_mode(object):
    def setupUi(self, DOOR_mode):
        DOOR_mode.setObjectName("DOOR_mode")
        DOOR_mode.resize(782, 520)
        DOOR_mode.setSizeGripEnabled(True)
        self.label = QtWidgets.QLabel(DOOR_mode)
        self.label.setGeometry(QtCore.QRect(50, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Qlabel = QtWidgets.QLabel(DOOR_mode)
        self.Qlabel.setGeometry(QtCore.QRect(50, 80, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Qlabel.setFont(font)
        self.Qlabel.setObjectName("Qlabel")
        self.formLayoutWidget = QtWidgets.QWidget(DOOR_mode)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 120, 421, 331))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.comboBox_23 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.setItemText(0, "")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_23)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_6 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.comboBox_8 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(0, "")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.comboBox_7 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboBox_26 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.setItemText(0, "")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_26)
        self.comboBox_27 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.comboBox_27.setItemText(0, "")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_27)
        self.comboBox_28 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.setItemText(0, "")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_28)
        self.comboBox_29 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.setItemText(0, "")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox_29)
        self.pushButton = QtWidgets.QPushButton(DOOR_mode)
        self.pushButton.setGeometry(QtCore.QRect(520, 460, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(DOOR_mode)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 460, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(DOOR_mode)
        QtCore.QMetaObject.connectSlotsByName(DOOR_mode)

    def retranslateUi(self, DOOR_mode):
        _translate = QtCore.QCoreApplication.translate
        DOOR_mode.setWindowTitle(_translate("DOOR_mode", "DOOR Parameters Change"))
        self.label.setText(_translate("DOOR_mode", "Mode:DOOR"))
        self.Qlabel.setText(_translate("DOOR_mode", "View and Change your parameters"))
        self.label_3.setText(_translate("DOOR_mode", "LOWER RATE LIMIT(PPM)"))
        self.label_4.setText(_translate("DOOR_mode", "UPPER RATE LIMIT(PPM)"))
        self.label_25.setText(_translate("DOOR_mode", "MAXIMUM SENSOR RATE(PPM)"))
        self.comboBox_23.setItemText(1, _translate("DOOR_mode", "50"))
        self.comboBox_23.setItemText(2, _translate("DOOR_mode", "55"))
        self.comboBox_23.setItemText(3, _translate("DOOR_mode", "60"))
        self.comboBox_23.setItemText(4, _translate("DOOR_mode", "65"))
        self.comboBox_23.setItemText(5, _translate("DOOR_mode", "70"))
        self.comboBox_23.setItemText(6, _translate("DOOR_mode", "75"))
        self.comboBox_23.setItemText(7, _translate("DOOR_mode", "80"))
        self.comboBox_23.setItemText(8, _translate("DOOR_mode", "85"))
        self.comboBox_23.setItemText(9, _translate("DOOR_mode", "90"))
        self.comboBox_23.setItemText(10, _translate("DOOR_mode", "95"))
        self.comboBox_23.setItemText(11, _translate("DOOR_mode", "100"))
        self.comboBox_23.setItemText(12, _translate("DOOR_mode", "105"))
        self.comboBox_23.setItemText(13, _translate("DOOR_mode", "110"))
        self.comboBox_23.setItemText(14, _translate("DOOR_mode", "115"))
        self.comboBox_23.setItemText(15, _translate("DOOR_mode", "120"))
        self.comboBox_23.setItemText(16, _translate("DOOR_mode", "125"))
        self.comboBox_23.setItemText(17, _translate("DOOR_mode", "130"))
        self.comboBox_23.setItemText(18, _translate("DOOR_mode", "135"))
        self.comboBox_23.setItemText(19, _translate("DOOR_mode", "140"))
        self.comboBox_23.setItemText(20, _translate("DOOR_mode", "145"))
        self.comboBox_23.setItemText(21, _translate("DOOR_mode", "150"))
        self.comboBox_23.setItemText(22, _translate("DOOR_mode", "155"))
        self.comboBox_23.setItemText(23, _translate("DOOR_mode", "160"))
        self.comboBox_23.setItemText(24, _translate("DOOR_mode", "165"))
        self.comboBox_23.setItemText(25, _translate("DOOR_mode", "170"))
        self.comboBox_23.setItemText(26, _translate("DOOR_mode", "175"))
        self.comboBox_5.setItemText(1, _translate("DOOR_mode", "30"))
        self.comboBox_5.setItemText(2, _translate("DOOR_mode", "35"))
        self.comboBox_5.setItemText(3, _translate("DOOR_mode", "40"))
        self.comboBox_5.setItemText(4, _translate("DOOR_mode", "45"))
        self.comboBox_5.setItemText(5, _translate("DOOR_mode", "50"))
        self.comboBox_5.setItemText(6, _translate("DOOR_mode", "51"))
        self.comboBox_5.setItemText(7, _translate("DOOR_mode", "52"))
        self.comboBox_5.setItemText(8, _translate("DOOR_mode", "53"))
        self.comboBox_5.setItemText(9, _translate("DOOR_mode", "54"))
        self.comboBox_5.setItemText(10, _translate("DOOR_mode", "55"))
        self.comboBox_5.setItemText(11, _translate("DOOR_mode", "56"))
        self.comboBox_5.setItemText(12, _translate("DOOR_mode", "57"))
        self.comboBox_5.setItemText(13, _translate("DOOR_mode", "58"))
        self.comboBox_5.setItemText(14, _translate("DOOR_mode", "59"))
        self.comboBox_5.setItemText(15, _translate("DOOR_mode", "60"))
        self.comboBox_5.setItemText(16, _translate("DOOR_mode", "61"))
        self.comboBox_5.setItemText(17, _translate("DOOR_mode", "62"))
        self.comboBox_5.setItemText(18, _translate("DOOR_mode", "63"))
        self.comboBox_5.setItemText(19, _translate("DOOR_mode", "64"))
        self.comboBox_5.setItemText(20, _translate("DOOR_mode", "65"))
        self.comboBox_5.setItemText(21, _translate("DOOR_mode", "66"))
        self.comboBox_5.setItemText(22, _translate("DOOR_mode", "67"))
        self.comboBox_5.setItemText(23, _translate("DOOR_mode", "68"))
        self.comboBox_5.setItemText(24, _translate("DOOR_mode", "69"))
        self.comboBox_5.setItemText(25, _translate("DOOR_mode", "70"))
        self.comboBox_5.setItemText(26, _translate("DOOR_mode", "71"))
        self.comboBox_5.setItemText(27, _translate("DOOR_mode", "72"))
        self.comboBox_5.setItemText(28, _translate("DOOR_mode", "73"))
        self.comboBox_5.setItemText(29, _translate("DOOR_mode", "74"))
        self.comboBox_5.setItemText(30, _translate("DOOR_mode", "75"))
        self.comboBox_5.setItemText(31, _translate("DOOR_mode", "76"))
        self.comboBox_5.setItemText(32, _translate("DOOR_mode", "77"))
        self.comboBox_5.setItemText(33, _translate("DOOR_mode", "78"))
        self.comboBox_5.setItemText(34, _translate("DOOR_mode", "79"))
        self.comboBox_5.setItemText(35, _translate("DOOR_mode", "80"))
        self.comboBox_5.setItemText(36, _translate("DOOR_mode", "81"))
        self.comboBox_5.setItemText(37, _translate("DOOR_mode", "82"))
        self.comboBox_5.setItemText(38, _translate("DOOR_mode", "83"))
        self.comboBox_5.setItemText(39, _translate("DOOR_mode", "84"))
        self.comboBox_5.setItemText(40, _translate("DOOR_mode", "85"))
        self.comboBox_5.setItemText(41, _translate("DOOR_mode", "86"))
        self.comboBox_5.setItemText(42, _translate("DOOR_mode", "87"))
        self.comboBox_5.setItemText(43, _translate("DOOR_mode", "88"))
        self.comboBox_5.setItemText(44, _translate("DOOR_mode", "89"))
        self.comboBox_5.setItemText(45, _translate("DOOR_mode", "90"))
        self.comboBox_5.setItemText(46, _translate("DOOR_mode", "95"))
        self.comboBox_5.setItemText(47, _translate("DOOR_mode", "100"))
        self.comboBox_5.setItemText(48, _translate("DOOR_mode", "105"))
        self.comboBox_5.setItemText(49, _translate("DOOR_mode", "110"))
        self.comboBox_5.setItemText(50, _translate("DOOR_mode", "115"))
        self.comboBox_5.setItemText(51, _translate("DOOR_mode", "120"))
        self.comboBox_5.setItemText(52, _translate("DOOR_mode", "125"))
        self.comboBox_5.setItemText(53, _translate("DOOR_mode", "130"))
        self.comboBox_5.setItemText(54, _translate("DOOR_mode", "135"))
        self.comboBox_5.setItemText(55, _translate("DOOR_mode", "140"))
        self.comboBox_5.setItemText(56, _translate("DOOR_mode", "145"))
        self.comboBox_5.setItemText(57, _translate("DOOR_mode", "150"))
        self.comboBox_5.setItemText(58, _translate("DOOR_mode", "155"))
        self.comboBox_5.setItemText(59, _translate("DOOR_mode", "160"))
        self.comboBox_5.setItemText(60, _translate("DOOR_mode", "165"))
        self.comboBox_5.setItemText(61, _translate("DOOR_mode", "170"))
        self.comboBox_5.setItemText(62, _translate("DOOR_mode", "175"))
        self.comboBox_4.setItemText(1, _translate("DOOR_mode", "50"))
        self.comboBox_4.setItemText(2, _translate("DOOR_mode", "55"))
        self.comboBox_4.setItemText(3, _translate("DOOR_mode", "60"))
        self.comboBox_4.setItemText(4, _translate("DOOR_mode", "65"))
        self.comboBox_4.setItemText(5, _translate("DOOR_mode", "70"))
        self.comboBox_4.setItemText(6, _translate("DOOR_mode", "75"))
        self.comboBox_4.setItemText(7, _translate("DOOR_mode", "80"))
        self.comboBox_4.setItemText(8, _translate("DOOR_mode", "85"))
        self.comboBox_4.setItemText(9, _translate("DOOR_mode", "90"))
        self.comboBox_4.setItemText(10, _translate("DOOR_mode", "95"))
        self.comboBox_4.setItemText(11, _translate("DOOR_mode", "100"))
        self.comboBox_4.setItemText(12, _translate("DOOR_mode", "105"))
        self.comboBox_4.setItemText(13, _translate("DOOR_mode", "110"))
        self.comboBox_4.setItemText(14, _translate("DOOR_mode", "115"))
        self.comboBox_4.setItemText(15, _translate("DOOR_mode", "120"))
        self.comboBox_4.setItemText(16, _translate("DOOR_mode", "125"))
        self.comboBox_4.setItemText(17, _translate("DOOR_mode", "130"))
        self.comboBox_4.setItemText(18, _translate("DOOR_mode", "135"))
        self.comboBox_4.setItemText(19, _translate("DOOR_mode", "140"))
        self.comboBox_4.setItemText(20, _translate("DOOR_mode", "145"))
        self.comboBox_4.setItemText(21, _translate("DOOR_mode", "150"))
        self.comboBox_4.setItemText(22, _translate("DOOR_mode", "155"))
        self.comboBox_4.setItemText(23, _translate("DOOR_mode", "160"))
        self.comboBox_4.setItemText(24, _translate("DOOR_mode", "165"))
        self.comboBox_4.setItemText(25, _translate("DOOR_mode", "170"))
        self.comboBox_4.setItemText(26, _translate("DOOR_mode", "175"))
        self.label_5.setText(_translate("DOOR_mode", "FIXED AV DELAY(ms)"))
        self.comboBox_3.setItemText(1, _translate("DOOR_mode", "70"))
        self.comboBox_3.setItemText(2, _translate("DOOR_mode", "80"))
        self.comboBox_3.setItemText(3, _translate("DOOR_mode", "90"))
        self.comboBox_3.setItemText(4, _translate("DOOR_mode", "100"))
        self.comboBox_3.setItemText(5, _translate("DOOR_mode", "110"))
        self.comboBox_3.setItemText(6, _translate("DOOR_mode", "120"))
        self.comboBox_3.setItemText(7, _translate("DOOR_mode", "130"))
        self.comboBox_3.setItemText(8, _translate("DOOR_mode", "140"))
        self.comboBox_3.setItemText(9, _translate("DOOR_mode", "150"))
        self.comboBox_3.setItemText(10, _translate("DOOR_mode", "160"))
        self.comboBox_3.setItemText(11, _translate("DOOR_mode", "170"))
        self.comboBox_3.setItemText(12, _translate("DOOR_mode", "180"))
        self.comboBox_3.setItemText(13, _translate("DOOR_mode", "190"))
        self.comboBox_3.setItemText(14, _translate("DOOR_mode", "200"))
        self.comboBox_3.setItemText(15, _translate("DOOR_mode", "210"))
        self.comboBox_3.setItemText(16, _translate("DOOR_mode", "220"))
        self.comboBox_3.setItemText(17, _translate("DOOR_mode", "230"))
        self.comboBox_3.setItemText(18, _translate("DOOR_mode", "240"))
        self.comboBox_3.setItemText(19, _translate("DOOR_mode", "250"))
        self.comboBox_3.setItemText(20, _translate("DOOR_mode", "260"))
        self.comboBox_3.setItemText(21, _translate("DOOR_mode", "270"))
        self.comboBox_3.setItemText(22, _translate("DOOR_mode", "280"))
        self.comboBox_3.setItemText(23, _translate("DOOR_mode", "290"))
        self.comboBox_3.setItemText(24, _translate("DOOR_mode", "300"))
        self.label_6.setText(_translate("DOOR_mode", "ATRIAL AMPLITUDE(V)"))
        self.label_9.setText(_translate("DOOR_mode", "VENTRICULAR AMPLITUDE(V)"))
        self.label_7.setText(_translate("DOOR_mode", "ATRIAL PULSE WIDTH(ms)"))
        self.label_8.setText(_translate("DOOR_mode", "VENTRICULAR PULSE WIDTH(ms)"))
        self.comboBox_6.setItemText(1, _translate("DOOR_mode", "1.25"))
        self.comboBox_6.setItemText(2, _translate("DOOR_mode", "2.5"))
        self.comboBox_6.setItemText(3, _translate("DOOR_mode", "3.75"))
        self.comboBox_6.setItemText(4, _translate("DOOR_mode", "5.0"))
        self.comboBox_8.setItemText(1, _translate("DOOR_mode", "1.25"))
        self.comboBox_8.setItemText(2, _translate("DOOR_mode", "2.5"))
        self.comboBox_8.setItemText(3, _translate("DOOR_mode", "3.75"))
        self.comboBox_8.setItemText(4, _translate("DOOR_mode", "5.0"))
        self.comboBox_7.setItemText(1, _translate("DOOR_mode", "0.05"))
        self.comboBox_7.setItemText(2, _translate("DOOR_mode", "0.1"))
        self.comboBox_7.setItemText(3, _translate("DOOR_mode", "0.2"))
        self.comboBox_7.setItemText(4, _translate("DOOR_mode", "0.3"))
        self.comboBox_7.setItemText(5, _translate("DOOR_mode", "0.4"))
        self.comboBox_7.setItemText(6, _translate("DOOR_mode", "0.5"))
        self.comboBox_7.setItemText(7, _translate("DOOR_mode", "0.6"))
        self.comboBox_7.setItemText(8, _translate("DOOR_mode", "0.7"))
        self.comboBox_7.setItemText(9, _translate("DOOR_mode", "0.8"))
        self.comboBox_7.setItemText(10, _translate("DOOR_mode", "0.9"))
        self.comboBox_7.setItemText(11, _translate("DOOR_mode", "1.0"))
        self.comboBox_7.setItemText(12, _translate("DOOR_mode", "1.1"))
        self.comboBox_7.setItemText(13, _translate("DOOR_mode", "1.2"))
        self.comboBox_7.setItemText(14, _translate("DOOR_mode", "1.3"))
        self.comboBox_7.setItemText(15, _translate("DOOR_mode", "1.4"))
        self.comboBox_7.setItemText(16, _translate("DOOR_mode", "1.5"))
        self.comboBox_7.setItemText(17, _translate("DOOR_mode", "1.6"))
        self.comboBox_7.setItemText(18, _translate("DOOR_mode", "1.7"))
        self.comboBox_7.setItemText(19, _translate("DOOR_mode", "1.8"))
        self.comboBox_7.setItemText(20, _translate("DOOR_mode", "1.9"))
        self.comboBox_2.setItemText(1, _translate("DOOR_mode", "0.05"))
        self.comboBox_2.setItemText(2, _translate("DOOR_mode", "0.1"))
        self.comboBox_2.setItemText(3, _translate("DOOR_mode", "0.2"))
        self.comboBox_2.setItemText(4, _translate("DOOR_mode", "0.3"))
        self.comboBox_2.setItemText(5, _translate("DOOR_mode", "0.4"))
        self.comboBox_2.setItemText(6, _translate("DOOR_mode", "0.5"))
        self.comboBox_2.setItemText(7, _translate("DOOR_mode", "0.6"))
        self.comboBox_2.setItemText(8, _translate("DOOR_mode", "0.7"))
        self.comboBox_2.setItemText(9, _translate("DOOR_mode", "0.8"))
        self.comboBox_2.setItemText(10, _translate("DOOR_mode", "0.9"))
        self.comboBox_2.setItemText(11, _translate("DOOR_mode", "1.0"))
        self.comboBox_2.setItemText(12, _translate("DOOR_mode", "1.1"))
        self.comboBox_2.setItemText(13, _translate("DOOR_mode", "1.2"))
        self.comboBox_2.setItemText(14, _translate("DOOR_mode", "1.3"))
        self.comboBox_2.setItemText(15, _translate("DOOR_mode", "1.4"))
        self.comboBox_2.setItemText(16, _translate("DOOR_mode", "1.5"))
        self.comboBox_2.setItemText(17, _translate("DOOR_mode", "1.6"))
        self.comboBox_2.setItemText(18, _translate("DOOR_mode", "1.7"))
        self.comboBox_2.setItemText(19, _translate("DOOR_mode", "1.8"))
        self.comboBox_2.setItemText(20, _translate("DOOR_mode", "1.9"))
        self.label_28.setText(_translate("DOOR_mode", "ACTIVITY THRESHOLD"))
        self.label_29.setText(_translate("DOOR_mode", "REACTION TIME (s)"))
        self.label_30.setText(_translate("DOOR_mode", "RESPONSE FACTOR"))
        self.label_31.setText(_translate("DOOR_mode", "RECOVERY TIME (min)"))
        self.comboBox_26.setItemText(1, _translate("DOOR_mode", "V-LOW"))
        self.comboBox_26.setItemText(2, _translate("DOOR_mode", "LOW"))
        self.comboBox_26.setItemText(3, _translate("DOOR_mode", "MED-LOW"))
        self.comboBox_26.setItemText(4, _translate("DOOR_mode", "MED"))
        self.comboBox_26.setItemText(5, _translate("DOOR_mode", "MED-HIGH"))
        self.comboBox_26.setItemText(6, _translate("DOOR_mode", "HIGH"))
        self.comboBox_26.setItemText(7, _translate("DOOR_mode", "V-HIGH"))
        self.comboBox_27.setItemText(1, _translate("DOOR_mode", "10"))
        self.comboBox_27.setItemText(2, _translate("DOOR_mode", "20"))
        self.comboBox_27.setItemText(3, _translate("DOOR_mode", "30"))
        self.comboBox_27.setItemText(4, _translate("DOOR_mode", "40"))
        self.comboBox_27.setItemText(5, _translate("DOOR_mode", "50"))
        self.comboBox_28.setItemText(1, _translate("DOOR_mode", "1"))
        self.comboBox_28.setItemText(2, _translate("DOOR_mode", "2"))
        self.comboBox_28.setItemText(3, _translate("DOOR_mode", "3"))
        self.comboBox_28.setItemText(4, _translate("DOOR_mode", "4"))
        self.comboBox_28.setItemText(5, _translate("DOOR_mode", "5"))
        self.comboBox_28.setItemText(6, _translate("DOOR_mode", "6"))
        self.comboBox_28.setItemText(7, _translate("DOOR_mode", "7"))
        self.comboBox_28.setItemText(8, _translate("DOOR_mode", "8"))
        self.comboBox_28.setItemText(9, _translate("DOOR_mode", "9"))
        self.comboBox_28.setItemText(10, _translate("DOOR_mode", "10"))
        self.comboBox_28.setItemText(11, _translate("DOOR_mode", "11"))
        self.comboBox_28.setItemText(12, _translate("DOOR_mode", "12"))
        self.comboBox_28.setItemText(13, _translate("DOOR_mode", "13"))
        self.comboBox_28.setItemText(14, _translate("DOOR_mode", "14"))
        self.comboBox_28.setItemText(15, _translate("DOOR_mode", "15"))
        self.comboBox_28.setItemText(16, _translate("DOOR_mode", "16"))
        self.comboBox_29.setItemText(1, _translate("DOOR_mode", "2"))
        self.comboBox_29.setItemText(2, _translate("DOOR_mode", "3"))
        self.comboBox_29.setItemText(3, _translate("DOOR_mode", "4"))
        self.comboBox_29.setItemText(4, _translate("DOOR_mode", "5"))
        self.comboBox_29.setItemText(5, _translate("DOOR_mode", "6"))
        self.comboBox_29.setItemText(6, _translate("DOOR_mode", "7"))
        self.comboBox_29.setItemText(7, _translate("DOOR_mode", "8"))
        self.comboBox_29.setItemText(8, _translate("DOOR_mode", "9"))
        self.comboBox_29.setItemText(9, _translate("DOOR_mode", "10"))
        self.comboBox_29.setItemText(10, _translate("DOOR_mode", "11"))
        self.comboBox_29.setItemText(11, _translate("DOOR_mode", "12"))
        self.comboBox_29.setItemText(12, _translate("DOOR_mode", "13"))
        self.comboBox_29.setItemText(13, _translate("DOOR_mode", "14"))
        self.comboBox_29.setItemText(14, _translate("DOOR_mode", "15"))
        self.comboBox_29.setItemText(15, _translate("DOOR_mode", "16"))
        self.pushButton.setText(_translate("DOOR_mode", "Confirm"))
        self.pushButton_2.setText(_translate("DOOR_mode", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DOOR_mode = QtWidgets.QDialog()
    ui = Ui_DOOR_mode()
    ui.setupUi(DOOR_mode)
    DOOR_mode.show()
    sys.exit(app.exec_())
