# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\New folder\VVI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VVI_mode(object):
    def setupUi(self, VVI_mode):
        VVI_mode.setObjectName("VVI_mode")
        VVI_mode.resize(700, 400)
        VVI_mode.setSizeGripEnabled(True)
        self.label = QtWidgets.QLabel(VVI_mode)
        self.label.setGeometry(QtCore.QRect(20, 20, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(VVI_mode)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(VVI_mode)
        self.pushButton.setGeometry(QtCore.QRect(430, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(VVI_mode)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 350, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayoutWidget = QtWidgets.QWidget(VVI_mode)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 110, 381, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_11 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.setItemText(0, "")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.comboBox_17 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.setItemText(0, "")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_17)
        self.comboBox_16 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.setItemText(0, "")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_16)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)

        self.retranslateUi(VVI_mode)
        QtCore.QMetaObject.connectSlotsByName(VVI_mode)

    def retranslateUi(self, VVI_mode):
        _translate = QtCore.QCoreApplication.translate
        VVI_mode.setWindowTitle(_translate("VVI_mode", "VVI Parameter Change"))
        self.label.setText(_translate("VVI_mode", "Mode:VVI"))
        self.label_2.setText(_translate("VVI_mode", "View and Change your parameters"))
        self.pushButton.setText(_translate("VVI_mode", "Confirm"))
        self.pushButton_2.setText(_translate("VVI_mode", "Back"))
        self.label_3.setText(_translate("VVI_mode", "LOWER RATE LIMIT(PPM)"))
        self.comboBox_5.setItemText(1, _translate("VVI_mode", "30"))
        self.comboBox_5.setItemText(2, _translate("VVI_mode", "35"))
        self.comboBox_5.setItemText(3, _translate("VVI_mode", "40"))
        self.comboBox_5.setItemText(4, _translate("VVI_mode", "45"))
        self.comboBox_5.setItemText(5, _translate("VVI_mode", "50"))
        self.comboBox_5.setItemText(6, _translate("VVI_mode", "51"))
        self.comboBox_5.setItemText(7, _translate("VVI_mode", "52"))
        self.comboBox_5.setItemText(8, _translate("VVI_mode", "53"))
        self.comboBox_5.setItemText(9, _translate("VVI_mode", "54"))
        self.comboBox_5.setItemText(10, _translate("VVI_mode", "55"))
        self.comboBox_5.setItemText(11, _translate("VVI_mode", "56"))
        self.comboBox_5.setItemText(12, _translate("VVI_mode", "57"))
        self.comboBox_5.setItemText(13, _translate("VVI_mode", "58"))
        self.comboBox_5.setItemText(14, _translate("VVI_mode", "59"))
        self.comboBox_5.setItemText(15, _translate("VVI_mode", "60"))
        self.comboBox_5.setItemText(16, _translate("VVI_mode", "61"))
        self.comboBox_5.setItemText(17, _translate("VVI_mode", "62"))
        self.comboBox_5.setItemText(18, _translate("VVI_mode", "63"))
        self.comboBox_5.setItemText(19, _translate("VVI_mode", "64"))
        self.comboBox_5.setItemText(20, _translate("VVI_mode", "65"))
        self.comboBox_5.setItemText(21, _translate("VVI_mode", "66"))
        self.comboBox_5.setItemText(22, _translate("VVI_mode", "67"))
        self.comboBox_5.setItemText(23, _translate("VVI_mode", "68"))
        self.comboBox_5.setItemText(24, _translate("VVI_mode", "69"))
        self.comboBox_5.setItemText(25, _translate("VVI_mode", "70"))
        self.comboBox_5.setItemText(26, _translate("VVI_mode", "71"))
        self.comboBox_5.setItemText(27, _translate("VVI_mode", "72"))
        self.comboBox_5.setItemText(28, _translate("VVI_mode", "73"))
        self.comboBox_5.setItemText(29, _translate("VVI_mode", "74"))
        self.comboBox_5.setItemText(30, _translate("VVI_mode", "75"))
        self.comboBox_5.setItemText(31, _translate("VVI_mode", "76"))
        self.comboBox_5.setItemText(32, _translate("VVI_mode", "77"))
        self.comboBox_5.setItemText(33, _translate("VVI_mode", "78"))
        self.comboBox_5.setItemText(34, _translate("VVI_mode", "79"))
        self.comboBox_5.setItemText(35, _translate("VVI_mode", "80"))
        self.comboBox_5.setItemText(36, _translate("VVI_mode", "81"))
        self.comboBox_5.setItemText(37, _translate("VVI_mode", "82"))
        self.comboBox_5.setItemText(38, _translate("VVI_mode", "83"))
        self.comboBox_5.setItemText(39, _translate("VVI_mode", "84"))
        self.comboBox_5.setItemText(40, _translate("VVI_mode", "85"))
        self.comboBox_5.setItemText(41, _translate("VVI_mode", "86"))
        self.comboBox_5.setItemText(42, _translate("VVI_mode", "87"))
        self.comboBox_5.setItemText(43, _translate("VVI_mode", "88"))
        self.comboBox_5.setItemText(44, _translate("VVI_mode", "89"))
        self.comboBox_5.setItemText(45, _translate("VVI_mode", "90"))
        self.comboBox_5.setItemText(46, _translate("VVI_mode", "95"))
        self.comboBox_5.setItemText(47, _translate("VVI_mode", "100"))
        self.comboBox_5.setItemText(48, _translate("VVI_mode", "105"))
        self.comboBox_5.setItemText(49, _translate("VVI_mode", "110"))
        self.comboBox_5.setItemText(50, _translate("VVI_mode", "115"))
        self.comboBox_5.setItemText(51, _translate("VVI_mode", "120"))
        self.comboBox_5.setItemText(52, _translate("VVI_mode", "125"))
        self.comboBox_5.setItemText(53, _translate("VVI_mode", "130"))
        self.comboBox_5.setItemText(54, _translate("VVI_mode", "135"))
        self.comboBox_5.setItemText(55, _translate("VVI_mode", "140"))
        self.comboBox_5.setItemText(56, _translate("VVI_mode", "145"))
        self.comboBox_5.setItemText(57, _translate("VVI_mode", "150"))
        self.comboBox_5.setItemText(58, _translate("VVI_mode", "155"))
        self.comboBox_5.setItemText(59, _translate("VVI_mode", "160"))
        self.comboBox_5.setItemText(60, _translate("VVI_mode", "165"))
        self.comboBox_5.setItemText(61, _translate("VVI_mode", "170"))
        self.comboBox_5.setItemText(62, _translate("VVI_mode", "175"))
        self.label_4.setText(_translate("VVI_mode", "UPPER RATE LIMIT(PPM)"))
        self.comboBox_4.setItemText(1, _translate("VVI_mode", "50"))
        self.comboBox_4.setItemText(2, _translate("VVI_mode", "55"))
        self.comboBox_4.setItemText(3, _translate("VVI_mode", "60"))
        self.comboBox_4.setItemText(4, _translate("VVI_mode", "65"))
        self.comboBox_4.setItemText(5, _translate("VVI_mode", "70"))
        self.comboBox_4.setItemText(6, _translate("VVI_mode", "75"))
        self.comboBox_4.setItemText(7, _translate("VVI_mode", "80"))
        self.comboBox_4.setItemText(8, _translate("VVI_mode", "85"))
        self.comboBox_4.setItemText(9, _translate("VVI_mode", "90"))
        self.comboBox_4.setItemText(10, _translate("VVI_mode", "95"))
        self.comboBox_4.setItemText(11, _translate("VVI_mode", "100"))
        self.comboBox_4.setItemText(12, _translate("VVI_mode", "105"))
        self.comboBox_4.setItemText(13, _translate("VVI_mode", "110"))
        self.comboBox_4.setItemText(14, _translate("VVI_mode", "115"))
        self.comboBox_4.setItemText(15, _translate("VVI_mode", "120"))
        self.comboBox_4.setItemText(16, _translate("VVI_mode", "125"))
        self.comboBox_4.setItemText(17, _translate("VVI_mode", "130"))
        self.comboBox_4.setItemText(18, _translate("VVI_mode", "135"))
        self.comboBox_4.setItemText(19, _translate("VVI_mode", "140"))
        self.comboBox_4.setItemText(20, _translate("VVI_mode", "145"))
        self.comboBox_4.setItemText(21, _translate("VVI_mode", "150"))
        self.comboBox_4.setItemText(22, _translate("VVI_mode", "155"))
        self.comboBox_4.setItemText(23, _translate("VVI_mode", "160"))
        self.comboBox_4.setItemText(24, _translate("VVI_mode", "165"))
        self.comboBox_4.setItemText(25, _translate("VVI_mode", "170"))
        self.comboBox_4.setItemText(26, _translate("VVI_mode", "175"))
        self.label_5.setText(_translate("VVI_mode", "VENTRICULAR AMPLITUDE(V)"))
        self.comboBox_3.setItemText(1, _translate("VVI_mode", "1.25"))
        self.comboBox_3.setItemText(2, _translate("VVI_mode", "2.5"))
        self.comboBox_3.setItemText(3, _translate("VVI_mode", "3.75"))
        self.comboBox_3.setItemText(4, _translate("VVI_mode", "5.0"))
        self.label_7.setText(_translate("VVI_mode", "VENTRICULAR PULSE WIDTH(ms)"))
        self.comboBox_2.setItemText(1, _translate("VVI_mode", "0.05"))
        self.comboBox_2.setItemText(2, _translate("VVI_mode", "0.1"))
        self.comboBox_2.setItemText(3, _translate("VVI_mode", "0.2"))
        self.comboBox_2.setItemText(4, _translate("VVI_mode", "0.3"))
        self.comboBox_2.setItemText(5, _translate("VVI_mode", "0.4"))
        self.comboBox_2.setItemText(6, _translate("VVI_mode", "0.5"))
        self.comboBox_2.setItemText(7, _translate("VVI_mode", "0.6"))
        self.comboBox_2.setItemText(8, _translate("VVI_mode", "0.7"))
        self.comboBox_2.setItemText(9, _translate("VVI_mode", "0.8"))
        self.comboBox_2.setItemText(10, _translate("VVI_mode", "0.9"))
        self.comboBox_2.setItemText(11, _translate("VVI_mode", "1.0"))
        self.comboBox_2.setItemText(12, _translate("VVI_mode", "1.1"))
        self.comboBox_2.setItemText(13, _translate("VVI_mode", "1.2"))
        self.comboBox_2.setItemText(14, _translate("VVI_mode", "1.3"))
        self.comboBox_2.setItemText(15, _translate("VVI_mode", "1.4"))
        self.comboBox_2.setItemText(16, _translate("VVI_mode", "1.5"))
        self.comboBox_2.setItemText(17, _translate("VVI_mode", "1.6"))
        self.comboBox_2.setItemText(18, _translate("VVI_mode", "1.7"))
        self.comboBox_2.setItemText(19, _translate("VVI_mode", "1.8"))
        self.comboBox_2.setItemText(20, _translate("VVI_mode", "1.9"))
        self.label_13.setText(_translate("VVI_mode", "VENTRICULAR SENSITIVITY (mV)"))
        self.comboBox_11.setItemText(1, _translate("VVI_mode", "0.25"))
        self.comboBox_11.setItemText(2, _translate("VVI_mode", "0.5"))
        self.comboBox_11.setItemText(3, _translate("VVI_mode", "0.75"))
        self.comboBox_11.setItemText(4, _translate("VVI_mode", "1.0"))
        self.comboBox_11.setItemText(5, _translate("VVI_mode", "1.5"))
        self.comboBox_11.setItemText(6, _translate("VVI_mode", "2.0"))
        self.comboBox_11.setItemText(7, _translate("VVI_mode", "2.5"))
        self.comboBox_11.setItemText(8, _translate("VVI_mode", "3.0"))
        self.comboBox_11.setItemText(9, _translate("VVI_mode", "3.5"))
        self.comboBox_11.setItemText(10, _translate("VVI_mode", "4.0"))
        self.comboBox_11.setItemText(11, _translate("VVI_mode", "4.5"))
        self.comboBox_11.setItemText(12, _translate("VVI_mode", "5.0"))
        self.comboBox_11.setItemText(13, _translate("VVI_mode", "5.5"))
        self.comboBox_11.setItemText(14, _translate("VVI_mode", "6.0"))
        self.comboBox_11.setItemText(15, _translate("VVI_mode", "6.5"))
        self.comboBox_11.setItemText(16, _translate("VVI_mode", "7.0"))
        self.comboBox_11.setItemText(17, _translate("VVI_mode", "7.5"))
        self.comboBox_11.setItemText(18, _translate("VVI_mode", "8.0"))
        self.comboBox_11.setItemText(19, _translate("VVI_mode", "8.5"))
        self.comboBox_11.setItemText(20, _translate("VVI_mode", "9.0"))
        self.comboBox_11.setItemText(21, _translate("VVI_mode", "9.5"))
        self.comboBox_11.setItemText(22, _translate("VVI_mode", "10.0"))
        self.label_9.setText(_translate("VVI_mode", "VRP(ms)"))
        self.comboBox.setItemText(1, _translate("VVI_mode", "150"))
        self.comboBox.setItemText(2, _translate("VVI_mode", "160"))
        self.comboBox.setItemText(3, _translate("VVI_mode", "170"))
        self.comboBox.setItemText(4, _translate("VVI_mode", "180"))
        self.comboBox.setItemText(5, _translate("VVI_mode", "190"))
        self.comboBox.setItemText(6, _translate("VVI_mode", "200"))
        self.comboBox.setItemText(7, _translate("VVI_mode", "210"))
        self.comboBox.setItemText(8, _translate("VVI_mode", "220"))
        self.comboBox.setItemText(9, _translate("VVI_mode", "230"))
        self.comboBox.setItemText(10, _translate("VVI_mode", "240"))
        self.comboBox.setItemText(11, _translate("VVI_mode", "250"))
        self.comboBox.setItemText(12, _translate("VVI_mode", "260"))
        self.comboBox.setItemText(13, _translate("VVI_mode", "270"))
        self.comboBox.setItemText(14, _translate("VVI_mode", "280"))
        self.comboBox.setItemText(15, _translate("VVI_mode", "290"))
        self.comboBox.setItemText(16, _translate("VVI_mode", "300"))
        self.comboBox.setItemText(17, _translate("VVI_mode", "310"))
        self.comboBox.setItemText(18, _translate("VVI_mode", "320"))
        self.comboBox.setItemText(19, _translate("VVI_mode", "330"))
        self.comboBox.setItemText(20, _translate("VVI_mode", "340"))
        self.comboBox.setItemText(21, _translate("VVI_mode", "350"))
        self.comboBox.setItemText(22, _translate("VVI_mode", "360"))
        self.comboBox.setItemText(23, _translate("VVI_mode", "370"))
        self.comboBox.setItemText(24, _translate("VVI_mode", "380"))
        self.comboBox.setItemText(25, _translate("VVI_mode", "390"))
        self.comboBox.setItemText(26, _translate("VVI_mode", "400"))
        self.comboBox.setItemText(27, _translate("VVI_mode", "410"))
        self.comboBox.setItemText(28, _translate("VVI_mode", "420"))
        self.comboBox.setItemText(29, _translate("VVI_mode", "430"))
        self.comboBox.setItemText(30, _translate("VVI_mode", "440"))
        self.comboBox.setItemText(31, _translate("VVI_mode", "450"))
        self.comboBox.setItemText(32, _translate("VVI_mode", "460"))
        self.comboBox.setItemText(33, _translate("VVI_mode", "470"))
        self.comboBox.setItemText(34, _translate("VVI_mode", "480"))
        self.comboBox.setItemText(35, _translate("VVI_mode", "490"))
        self.comboBox.setItemText(36, _translate("VVI_mode", "500"))
        self.label_18.setText(_translate("VVI_mode", "HYSTERESIS"))
        self.comboBox_17.setItemText(1, _translate("VVI_mode", "OFF"))
        self.comboBox_17.setItemText(2, _translate("VVI_mode", "30"))
        self.comboBox_17.setItemText(3, _translate("VVI_mode", "35"))
        self.comboBox_17.setItemText(4, _translate("VVI_mode", "40"))
        self.comboBox_17.setItemText(5, _translate("VVI_mode", "45"))
        self.comboBox_17.setItemText(6, _translate("VVI_mode", "50"))
        self.comboBox_17.setItemText(7, _translate("VVI_mode", "51"))
        self.comboBox_17.setItemText(8, _translate("VVI_mode", "52"))
        self.comboBox_17.setItemText(9, _translate("VVI_mode", "53"))
        self.comboBox_17.setItemText(10, _translate("VVI_mode", "54"))
        self.comboBox_17.setItemText(11, _translate("VVI_mode", "55"))
        self.comboBox_17.setItemText(12, _translate("VVI_mode", "56"))
        self.comboBox_17.setItemText(13, _translate("VVI_mode", "57"))
        self.comboBox_17.setItemText(14, _translate("VVI_mode", "58"))
        self.comboBox_17.setItemText(15, _translate("VVI_mode", "59"))
        self.comboBox_17.setItemText(16, _translate("VVI_mode", "60"))
        self.comboBox_17.setItemText(17, _translate("VVI_mode", "61"))
        self.comboBox_17.setItemText(18, _translate("VVI_mode", "62"))
        self.comboBox_17.setItemText(19, _translate("VVI_mode", "63"))
        self.comboBox_17.setItemText(20, _translate("VVI_mode", "64"))
        self.comboBox_17.setItemText(21, _translate("VVI_mode", "65"))
        self.comboBox_17.setItemText(22, _translate("VVI_mode", "66"))
        self.comboBox_17.setItemText(23, _translate("VVI_mode", "67"))
        self.comboBox_17.setItemText(24, _translate("VVI_mode", "68"))
        self.comboBox_17.setItemText(25, _translate("VVI_mode", "69"))
        self.comboBox_17.setItemText(26, _translate("VVI_mode", "70"))
        self.comboBox_17.setItemText(27, _translate("VVI_mode", "71"))
        self.comboBox_17.setItemText(28, _translate("VVI_mode", "72"))
        self.comboBox_17.setItemText(29, _translate("VVI_mode", "73"))
        self.comboBox_17.setItemText(30, _translate("VVI_mode", "74"))
        self.comboBox_17.setItemText(31, _translate("VVI_mode", "75"))
        self.comboBox_17.setItemText(32, _translate("VVI_mode", "76"))
        self.comboBox_17.setItemText(33, _translate("VVI_mode", "77"))
        self.comboBox_17.setItemText(34, _translate("VVI_mode", "78"))
        self.comboBox_17.setItemText(35, _translate("VVI_mode", "79"))
        self.comboBox_17.setItemText(36, _translate("VVI_mode", "80"))
        self.comboBox_17.setItemText(37, _translate("VVI_mode", "81"))
        self.comboBox_17.setItemText(38, _translate("VVI_mode", "82"))
        self.comboBox_17.setItemText(39, _translate("VVI_mode", "83"))
        self.comboBox_17.setItemText(40, _translate("VVI_mode", "84"))
        self.comboBox_17.setItemText(41, _translate("VVI_mode", "85"))
        self.comboBox_17.setItemText(42, _translate("VVI_mode", "86"))
        self.comboBox_17.setItemText(43, _translate("VVI_mode", "87"))
        self.comboBox_17.setItemText(44, _translate("VVI_mode", "88"))
        self.comboBox_17.setItemText(45, _translate("VVI_mode", "89"))
        self.comboBox_17.setItemText(46, _translate("VVI_mode", "90"))
        self.comboBox_17.setItemText(47, _translate("VVI_mode", "95"))
        self.comboBox_17.setItemText(48, _translate("VVI_mode", "100"))
        self.comboBox_17.setItemText(49, _translate("VVI_mode", "105"))
        self.comboBox_17.setItemText(50, _translate("VVI_mode", "110"))
        self.comboBox_17.setItemText(51, _translate("VVI_mode", "115"))
        self.comboBox_17.setItemText(52, _translate("VVI_mode", "120"))
        self.comboBox_17.setItemText(53, _translate("VVI_mode", "125"))
        self.comboBox_17.setItemText(54, _translate("VVI_mode", "130"))
        self.comboBox_17.setItemText(55, _translate("VVI_mode", "135"))
        self.comboBox_17.setItemText(56, _translate("VVI_mode", "140"))
        self.comboBox_17.setItemText(57, _translate("VVI_mode", "145"))
        self.comboBox_17.setItemText(58, _translate("VVI_mode", "150"))
        self.comboBox_17.setItemText(59, _translate("VVI_mode", "155"))
        self.comboBox_17.setItemText(60, _translate("VVI_mode", "160"))
        self.comboBox_17.setItemText(61, _translate("VVI_mode", "165"))
        self.comboBox_17.setItemText(62, _translate("VVI_mode", "170"))
        self.comboBox_17.setItemText(63, _translate("VVI_mode", "175"))
        self.comboBox_16.setItemText(1, _translate("VVI_mode", "OFF"))
        self.comboBox_16.setItemText(2, _translate("VVI_mode", "3"))
        self.comboBox_16.setItemText(3, _translate("VVI_mode", "6"))
        self.comboBox_16.setItemText(4, _translate("VVI_mode", "9"))
        self.comboBox_16.setItemText(5, _translate("VVI_mode", "12"))
        self.comboBox_16.setItemText(6, _translate("VVI_mode", "15"))
        self.comboBox_16.setItemText(7, _translate("VVI_mode", "18"))
        self.comboBox_16.setItemText(8, _translate("VVI_mode", "21"))
        self.comboBox_16.setItemText(9, _translate("VVI_mode", "25"))
        self.label_19.setText(_translate("VVI_mode", "RATE SMOOTHING (%)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VVI_mode = QtWidgets.QDialog()
    ui = Ui_VVI_mode()
    ui.setupUi(VVI_mode)
    VVI_mode.show()
    sys.exit(app.exec_())
